Make `appendToBody` work in Tooltip
valor-software/ng2-bootstrap pull request #1074
Opened 2016-10-04 18:52 UTC by jtomaszewski

If everything is already almost implemented, then why not just make this work?

If that's an "unclear" and "wrong" implementation, what is the correct one?
Can we put this one as a temporary one, so we don't have to fork it on our own?

2016-10-04 19:38 UTC, adrianfaciu commented
Can you please fix the lint issue.

2016-10-04 21:33 UTC, jtomaszewski commented
> Can you please fix the lint issue.

Fixed.

2016-10-04 21:59 UTC, valorkin commented
@jtomaszewski is positioning working properly?
can you please add sample to demo page?

2016-10-04 22:00 UTC, valorkin commented
Thanks a lot for your help :)

2016-10-05 07:28 UTC, jtomaszewski commented
> @jtomaszewski is positioning working properly?

Yes.

> can you please add sample to demo page?

Done ;)

2016-10-13 10:40 UTC, valorkin requested changes
ok, this review tool is completely new to me :)
please try to use appendNextToRoot
or it will not work from universal

2016-10-13 10:40 UTC, valorkin commented on components/tooltip/tooltip.directive.ts
> +      this.componentsHelper.getDocument().body.appendChild(this.tooltip.location.nativeElement);
can you use appendNextToRoot instead of appendChild?

2016-10-13 10:45 UTC, jtomaszewski commented on components/tooltip/tooltip.directive.ts
> +      this.componentsHelper.getDocument().body.appendChild(this.tooltip.location.nativeElement);
Sure. Anything else I should take care about? ;)

2016-10-13 11:28 UTC, valorkin commented on components/tooltip/tooltip.directive.ts
> +      this.componentsHelper.getDocument().body.appendChild(this.tooltip.location.nativeElement);
no, I suppose this one is the main one

2016-10-13 11:29 UTC, valorkin commented on components/tooltip/tooltip.directive.ts
> +      this.componentsHelper.getDocument().body.appendChild(this.tooltip.location.nativeElement);
you can check how it is done in tooltips for example

2016-10-22 14:43 UTC, jtomaszewski commented
I changed it to use `appendNextToRoot` method , squashed it into one commit and rebased to current development branch. IMHO it's good to merge ;)

2016-10-22 18:17 UTC, valorkin commented
This is awesome! Thank you!

2016-10-24 18:50 UTC, DethAriel commented
@valorkin are there any obstacles yet for merging this into master?

2016-10-24 19:56 UTC, valorkin approved these changes

2016-10-24 19:56 UTC, merged

2016-10-24 19:57 UTC, valorkin commented
Not at all, just stuck with AoT and routing a bit