- added typeaheadOnBlur event
valor-software/ng2-bootstrap pull request #1639
Opened 2017-02-13 15:49 UTC by imribarr-compit

- added documentation for typeaheadOnBlur
- removed tab event key since blur event handles it
- added getter to _active item

2017-02-13 15:55 UTC, SergeyKuryatnick commented
closes #1636

2017-02-15 13:58 UTC, valorkin requested changes

2017-02-15 13:58 UTC, valorkin commented on src/typeahead/typeahead.directive.ts
> -    if (e.keyCode === 9) {
all looks good except of this change, it should not be a part of adding onBlur output

2017-02-15 13:59 UTC, valorkin commented
@imribarr-compit looks good to me, but small change needed

2017-02-15 14:00 UTC, valorkin commented
BTW if you can add small test for this, it would be just awesome

2017-02-19 12:23 UTC, imribarr-compit commented on src/typeahead/typeahead.directive.ts
> -    if (e.keyCode === 9) {
I removed it since blur event handles it already, with this line, my change doesn't work.

2017-02-19 13:06 UTC, imribarr-compit commented on src/typeahead/typeahead.directive.ts
> -    if (e.keyCode === 9) {
Also, the only thing this line does is hides the results. This happens when the user blurs the component as well.

2017-02-20 06:55 UTC, imribarr-compit commented on src/typeahead/typeahead.directive.ts
> -    if (e.keyCode === 9) {
@valorkin

2017-02-28 12:10 UTC, imribarr-compit commented
@valorkin I've added a test for this. If you could just reply on my change request that would be great.

Thanks.

2017-02-28 21:14 UTC, valorkin approved these changes

2017-02-28 21:15 UTC, valorkin commented
Looks good to me!

2017-02-28 21:15 UTC, merged