feat(timepicker): added test plan
valor-software/ng2-bootstrap pull request #2127
Opened 2017-06-26 09:34 UTC by artemvfrolov

2017-07-11 13:53 UTC, SergeyKuryatnick requested changes

2017-07-11 13:53 UTC, SergeyKuryatnick commented on src/spec/timepicker/timepicker.utils.spec.ts
> +  it('should is no value', () => {
what?

2017-07-11 13:53 UTC, SergeyKuryatnick commented on src/spec/timepicker/timepicker.component.spec.ts
> +function testTime(hours?: number, minutes?: number, seconds?: number) {
You use this function in 3 specs - just move it to helper

2017-07-11 13:53 UTC, SergeyKuryatnick commented on src/spec/timepicker/timepicker.component.spec.ts
> +    // поле часы и минуты отображаются
Maybe all comments should be on english?

2017-07-11 13:53 UTC, SergeyKuryatnick commented on src/spec/timepicker/timepicker.component.spec.ts
> +      fixture.detectChanges();
Unneeded command in this test

2017-07-11 13:55 UTC, SergeyKuryatnick commented
Try not to use `fixture.detectChanges()` in all tests, only if it necessary  :)

2017-07-12 08:13 UTC, valorkin commented on src/spec/timepicker/timepicker.component.spec.ts
> +    // поле часы и минуты отображаются
it is for me, so I can check test case translations

2017-07-14 10:26 UTC, SergeyKuryatnick commented
Tests are failed. recheck pls.

2017-07-14 12:46 UTC, SergeyKuryatnick approved these changes

2017-07-14 12:52 UTC, merged