feat(popover & tooltip): add container classes
valor-software/ng2-bootstrap pull request #2190
Opened 2017-07-14 14:02 UTC by IlyaSurmay

added ability to apply custom css classes to tooltip and popover

2017-07-17 13:11 UTC, YevheniiaMazur commented
Tested, looks good

2017-07-18 09:37 UTC, valorkin requested changes

2017-07-18 09:37 UTC, valorkin commented on demo/src/app/components/+popover/demos/class/class.html
> +        popover="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." [containerClass]="'customClass'">
don't use `[]` binding for string setters
`[containerClass]="'customClass'"`
should be
`containerClass="customClass"`

2017-07-18 09:37 UTC, valorkin commented on demo/src/app/components/+popover/demos/index.ts
> +  class: {
using reserved keywords is no good

2017-07-18 09:37 UTC, valorkin commented on demo/src/app/components/+tooltip/demos/class/class.html
> +        tooltip="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." [containerClass]="'customClass'">
string setter

2017-07-18 12:54 UTC, merged