feat(modal): resolve modal data before OnInit
valor-software/ng2-bootstrap pull request #2600
Opened 2017-09-08 12:51 UTC by IlyaSurmay

Closes #2530

2017-09-22 11:55 UTC, nbelyh commented
Is there any chance for this to be merged in the next release?

2017-09-23 20:19 UTC, valorkin commented
I would say chances are 100%

2017-10-30 16:27 UTC, vanackere commented
Hi,

 Any ETA on merging this pull request ? This particular feature is very useful and it would be nice to have it on a released version.

2017-10-30 16:29 UTC, vanackere commented
Hi,

 Any ETA on merging this pull request ? This is a really useful feature and it would be really nice to have this in a real release.

2017-12-18 11:28 UTC, vanackere commented
Hi again,

 I've been running a local fork of ngx-bootstrap with this pull request applied in production for a few weeks with no problem (the alternative way of using a global service to pass parameters to the modals was definitely too ugly).
 It looks like 2.0.0-rc.0 is out but still misses this change... is anything particular - like known bugs or regressions- holding this from being merged ?

2017-12-18 13:40 UTC, valorkin commented
My time, it will be merged prior to releasing v2

2018-01-05 12:48 UTC, valorkin requested changes

2018-01-05 12:48 UTC, valorkin commented on src/component-loader/component-loader.class.ts
> +    data?: any; [key: string]: any;
`initialState`

2018-01-18 10:28 UTC, valorkin submitted a review, later dismissed

2018-01-18 11:17 UTC, YevheniiaMazur commented
Service modals do not work correctly - they are throwing error after opening and stop working (only reload page helps for closing)
![errorsmodals](https://user-images.githubusercontent.com/27342505/35095630-d73a43dc-fc51-11e7-8c84-c0774b9045c5.jpg)

2018-01-18 12:20 UTC, YevheniiaMazur commented
tested, looks good

2018-01-18 12:26 UTC, valorkin approved these changes

2018-01-18 12:43 UTC, merged