feat(tabs): add opportunity to add multiple classes to customClass attribute
valor-software/ng2-bootstrap pull request #2813
Opened 2017-10-06 20:34 UTC by LimarenkoDenis

#2467, #1508

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2017-10-10 09:58 UTC, IlyaSurmay commented
Hi, thanks for PR!
We can't merge it because looks like it hasn't been tested. This is what I get on tab init stage
![1507629364896](https://user-images.githubusercontent.com/18414330/31380649-9c36983e-adba-11e7-8c5a-e9b82fc3eec3.jpg)
Please, fix your PR, test it and update, then we'll merge it.

2017-10-10 09:59 UTC, IlyaSurmay commented on src/tabs/tab.directive.ts
> +    this._customClass.split(' ').forEach((element: string) => this.setElementClass = element);
this will throw an error if customClass isn't set

2017-10-10 10:02 UTC, IlyaSurmay requested changes

2017-10-10 10:02 UTC, IlyaSurmay commented on src/tabs/tab.directive.ts
> +    this._customClass.split(' ').forEach((element: string) => this.setElementClass = element);
this will throw an error if customClass isn't set

2017-10-10 10:02 UTC, IlyaSurmay commented on src/tabs/tab.directive.ts
> +    this.renderer.addClass(
what if list of classes changes? for example, if user pass `class-1 class-2` and then `class-2 class-3`. in this case all 3 classes will be appended

2017-10-18 13:41 UTC, merged

2017-10-18 13:41 UTC, valorkin commented
Thanks for PR :)