fix(timepicker): decompose mousewheel-arrowkeys
valor-software/ng2-bootstrap pull request #3555
Opened 2018-01-26 10:28 UTC by tarusin

decompose mousewheel-arrowkeys to mousewheel and arrow keys different demos

close #3546

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

2018-01-26 10:34 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/arrowkeys/arrowkeys.html
> +<p>Arrow keys disabled</p>
IMO it's better for each of these demos to have a button that disables/enables arrow keys or mosuewheel

2018-01-26 13:08 UTC, IlyaSurmay requested changes

2018-01-26 13:08 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/arrowkeys/arrowkeys.html
> +<timepicker [(ngModel)]="myTime2" [arrowkeys]="false" [readonlyInput]="!isEnabled"></timepicker>
readonly? initial idea was to disable enable the possibility to use arrow keys or mouse wheel. So it should look like this `[arrowkeys]="allowArrowKeys"`

2018-01-26 13:08 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/arrowkeys/arrowkeys.html
> +<button type="button" class="btn btn-info section bd-example" (click)="isEnabled=!isEnabled">Enable / Disable input</button>
spaces
`(click)="isEnabled = !isEnabled"`

2018-01-26 13:08 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/mousewheel/mousewheel.html
> +<timepicker [(ngModel)]="myTime1" [mousewheel]="false" [readonlyInput]="!isEnabled"></timepicker>
same, `[mousewheel]="allowMouseWheel"`

2018-01-26 14:06 UTC, IlyaSurmay requested changes

2018-01-26 14:06 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/arrowkeys/arrowkeys.html
> +<button type="button" class="btn btn-info section bd-example" (click)="allowArrowKeys = !allowArrowKeys">Enable / Disable input</button>
`Enable / Disable input` should be changed to `Enable / Disable arrow keys`

2018-01-26 14:06 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/arrowkeys/arrowkeys.ts
> +  myTime2: Date = new Date();
change to `myTime`

2018-01-26 14:06 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/mousewheel/mousewheel.html
> +<button type="button" class="btn btn-info section bd-example" (click)="allowMouseWheel = !allowMouseWheel">Enable / Disable input</button>
same

2018-01-26 14:06 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/mousewheel/mousewheel.ts
> +  myTime1: Date = new Date();
same

2018-01-26 15:27 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-09 16:09 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-12 12:01 UTC, YevheniiaMazur commented
Please, fix failed unit tests (maybe, rebase could help you)
![unitfail](https://user-images.githubusercontent.com/27342505/36096025-2e778da8-0ffd-11e8-9da1-2fc123e687f7.jpg)
![unitfaillog](https://user-images.githubusercontent.com/27342505/36096028-30959d00-0ffd-11e8-9226-6d54456cab5b.jpg)

2018-02-13 13:50 UTC, IlyaSurmay requested changes

2018-02-13 13:50 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/arrowkeys/arrowkeys.ts
> +  myTime: Date = new Date();
remove type annotation 
if type annotation isn't provided, typescript will use the type of the first assigned value

2018-02-13 13:50 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/mousewheel/mousewheel.ts
> +  myTime: Date = new Date();
same

2018-02-13 14:41 UTC, IlyaSurmay approved these changes

2018-02-15 12:00 UTC, YevheniiaMazur commented
Tested, looks good

2018-03-01 12:46 UTC, merged