docs(timepicker): add spinners demo
valor-software/ng2-bootstrap pull request #3578
Opened 2018-01-29 14:48 UTC by tarusin

adding demo with spinner property
close #3574

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-01-29 14:58 UTC, IlyaSurmay requested changes

2018-01-29 14:58 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/spinners/spinners.ts
> +  allowSpinners = true;
showSpinners

2018-01-29 14:58 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/spinners/spinners.ts
> +  ismeridian = false;
isMeridian

2018-01-29 14:58 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/demos/spinners/spinners.ts
> +  mytime: Date = new Date();
myTime / time

2018-01-29 15:13 UTC, IlyaSurmay approved these changes

2018-02-05 11:29 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-06 16:29 UTC, merged