docs(buttons): decompose radio and unchecked radio
valor-software/ng2-bootstrap pull request #3584
Opened 2018-01-30 12:33 UTC by tarusin

decompose radio and uncheckable radio demo to radio and uncheckable radio different demos
close #3581

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-01-30 13:06 UTC, IlyaSurmay requested changes

2018-01-30 13:06 UTC, IlyaSurmay commented on demo/src/app/components/+buttons/buttons-section.list.ts
> +        description: `<p>Radio buttons with unchecked state. Group can be created in two ways: using
There's no need to duplicate the info about creating button groups

2018-01-30 13:20 UTC, IlyaSurmay commented on demo/src/app/components/+buttons/buttons-section.list.ts
> +import {DemoButtonsUncheckableRadioComponent} from "./demos/uncheckable-radio/uncheckable-radio";
import { DemoButtonsUncheckableRadioComponent } from './demos/uncheckable-radio/uncheckable-radio';

2018-01-30 13:21 UTC, IlyaSurmay requested changes

2018-01-30 13:21 UTC, IlyaSurmay commented on demo/src/app/components/+buttons/buttons-section.list.ts
> +import {DemoButtonsUncheckableRadioComponent} from "./demos/uncheckable-radio/uncheckable-radio";
import { DemoButtonsUncheckableRadioComponent } from './demos/uncheckable-radio/uncheckable-radio';

2018-01-30 14:45 UTC, IlyaSurmay approved these changes

2018-02-05 12:49 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-06 16:29 UTC, merged