feat(timepicker): add validation for timepicker #3549 #3288
valor-software/ng2-bootstrap pull request #3588
Opened 2018-01-30 15:05 UTC by IraErshova

Add validation for timepicker based on ui-bootstrap validation.
Fix min-max validation issue.

close #3549 #3288

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-01-30 15:50 UTC, IlyaSurmay requested changes

2018-01-30 15:50 UTC, IlyaSurmay commented on src/timepicker/reducer/timepicker.reducer.ts
> +      if (state.config.max || state.config.min) {
looks like these 2 `if` could be one

2018-01-30 15:50 UTC, IlyaSurmay commented on src/timepicker/timepicker.component.ts
> +    const isValid = isHourInputValid(this.hours, this.isPM())
isInputLimitValid is called 3 times with the same parameters in this component, maybe it's better to make a function from it.

2018-01-31 12:31 UTC, IlyaSurmay submitted a review, later dismissed

2018-03-01 13:58 UTC, valorkin requested changes
please fix imports

2018-03-01 13:58 UTC, valorkin commented on src/timepicker/reducer/timepicker.actions.ts
> +import { Action } from '../../mini-ngrx';
`index` is must for system.js

2018-03-01 13:58 UTC, valorkin commented on src/timepicker/reducer/timepicker.actions.ts
> +import { Action } from '../../mini-ngrx';
and in other places of PR too

2018-03-01 15:39 UTC, YevheniiaMazur commented
Needs to fix conflicting files

2018-03-13 12:05 UTC, valorkin approved these changes

2018-03-29 09:13 UTC, valorkin approved these changes

2018-03-29 09:14 UTC, merged