docs(modal): add demo for scrolling long content
valor-software/ng2-bootstrap pull request #3592
Opened 2018-01-30 16:16 UTC by olshansky

close #3589

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-01-30 16:19 UTC, IlyaSurmay requested changes

2018-01-30 16:19 UTC, IlyaSurmay commented on demo/src/app/components/+modal/demos/scrolling-long-content/scrolling-long-content.html
> +    <ng-container *ngFor="let item of items">
no need for ng-container if there's just `<p>` inside. use <p *ngFor="let item of items">

2018-01-30 16:32 UTC, IlyaSurmay approved these changes

2018-02-05 12:58 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-06 16:30 UTC, merged