docs(datepicker): demo for supported formats, based on moment.js(1:1) #3590
valor-software/ng2-bootstrap pull request #3598
Opened 2018-01-31 10:50 UTC by IraErshova

Extend demo Custom date format in datepicker with several moment.js formats

Close #3590

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-01-31 11:35 UTC, IlyaSurmay requested changes
Be consistent in naming of files. If demo folder  is `custom-format`, then html and ts in it should have the same name. This is essential for generating plunkr and stackblitz demos.

2018-01-31 11:35 UTC, IlyaSurmay commented on demo/src/app/components/+datepicker/datepicker-section.list.ts
> +          <p>The following examples shows how to use a datepicker having <code>YYYY-MM-DD</code>, <code>MM/DD/YYYY</code>,
shows -> show

2018-01-31 12:40 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-05 13:25 UTC, YevheniiaMazur commented
Letter a marked as code, but it's not. And it will be better, if description of date format couldn't be splitting, and places at the same line
![smallissue](https://user-images.githubusercontent.com/27342505/35806616-c4c318b0-0a88-11e8-9616-d18efc63b8cc.jpg)
`

2018-02-08 11:40 UTC, YevheniiaMazur commented
Now checking prs is blocked by package issue.

2018-02-08 15:29 UTC, YevheniiaMazur commented
Tested, looks good

2018-03-01 12:42 UTC, merged