docs(collapse): add demo with show/hide methods
valor-software/ng2-bootstrap pull request #3599
Opened 2018-01-31 11:38 UTC by tarusin

close #3591

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-01-31 12:12 UTC, IlyaSurmay requested changes

2018-01-31 12:12 UTC, IlyaSurmay commented on demo/src/app/components/+collapse/demos/toggle-manual/toggle-manual.component.html
> +<div *ngIf="showSelected"
Why do we need a basic demo with `*ngIf` that doesn't even use CollapseDirective?

2018-01-31 12:12 UTC, IlyaSurmay commented on demo/src/app/components/+collapse/collapse-section.list.ts
> +        component: require('!!raw-loader?lang=typescript!./demos/basic/collapse-demo.component'),
ts and html files in folder should have the same names

2018-01-31 12:14 UTC, IlyaSurmay commented on demo/src/app/components/+collapse/demos/toggle-manual/toggle-manual.component.ts
> +    this.showSelected = true;
show / hide must be done without ngIf, using `hide()` and `show()` methods of `CollapseDirective`

2018-01-31 13:12 UTC, IlyaSurmay approved these changes

2018-02-05 13:43 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-06 16:31 UTC, merged