fix(demo): fix demo header static position for safari browser
valor-software/ng2-bootstrap pull request #3600
Opened 2018-01-31 12:06 UTC by olshansky

close #3312

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-01-31 12:33 UTC, EvilAlexei requested changes

2018-01-31 12:33 UTC, EvilAlexei commented on demo/src/assets/css/style.scss
> +  padding-top: 30px;
Why on .main-container and why 30px?

2018-01-31 12:52 UTC, olshansky commented on demo/src/assets/css/style.scss
> +  padding-top: 30px;
changed

2018-01-31 13:13 UTC, EvilAlexei requested changes

2018-01-31 13:13 UTC, EvilAlexei commented on demo/src/assets/css/style.scss
> +  .main {
Keep an order of elements. Header goes before Main :)

2018-01-31 13:17 UTC, EvilAlexei approved these changes

2018-02-21 14:02 UTC, YevheniiaMazur commented
Tested, looks good

2018-03-01 12:40 UTC, merged