fix(modals): fix minimize Safari after press esc
valor-software/ng2-bootstrap pull request #3605
Opened 2018-01-31 15:28 UTC by olshansky

fix: after opening any modal and pressing Esc button, browser minimize and only after that modal dissappears

close #3313

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.

2018-01-31 15:40 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-05 19:37 UTC, YevheniiaMazur commented
tested, looks good

2018-02-06 16:33 UTC, valorkin requested changes
TBD

2018-02-06 16:33 UTC, valorkin commented on src/modal/modal-container.component.ts
> +  @HostListener('keydown.esc', ['$event'])
if focus will be outside of modal 
what is possible without focus trap in place
pressing esc will not close modal

2018-03-13 12:05 UTC, valorkin approved these changes

2018-03-13 12:42 UTC, merged