fix(datepicker): remove position fixed
valor-software/ng2-bootstrap pull request #3610
Opened 2018-02-01 08:00 UTC by tarusin

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-01 13:18 UTC, IlyaSurmay requested changes

2018-02-01 13:18 UTC, IlyaSurmay commented on src/datepicker/bs-datepicker.component.ts
> +    this._outsideScrollListener = this._renderer.listen('document', 'scroll', () => {
Isn't this supposed to be in another PR? Also, this behavior should be disabled by default and this listener should only be created when corresponding input is set to true. input example `@Input() hideOnScroll = false`;

2018-02-01 13:18 UTC, IlyaSurmay commented on src/datepicker/bs-datepicker.scss
> -    left: 50% !important;
I thought we were only going to remove `position: fixed` and leave top and left

2018-02-01 16:07 UTC, IlyaSurmay requested changes

2018-02-01 16:07 UTC, IlyaSurmay commented on demo/src/app/components/+datepicker/datepicker-section.list.ts
> +        title: 'Manual datepicker',
This name doesn't reflect what demo is actually doing. Correct name is `Hide on scroll`

2018-02-08 09:16 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-08 09:34 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-09 15:50 UTC, IlyaSurmay approved these changes

2018-02-12 13:31 UTC, YevheniiaMazur commented
Tested, looks good

2018-03-01 12:37 UTC, merged