docs(timepicker): add isValid output demo #3612
valor-software/ng2-bootstrap pull request #3617
Opened 2018-02-01 12:45 UTC by IraErshova

Add isValid demo for timepicker

Close #3612

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-02-01 14:27 UTC, IlyaSurmay requested changes

2018-02-01 14:27 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/timepicker-section.list.ts
> +        <p>Illustrates emitting true if time value is a valid. You have to enter invalid time to see error.</p>
`isValid` event emits true if a value is a valid date. Enter an invalid date to see the error.

2018-02-08 14:27 UTC, IlyaSurmay approved these changes

2018-02-08 16:01 UTC, YevheniiaMazur commented
Tested, looks good

2018-03-01 12:33 UTC, valorkin approved these changes

2018-03-01 12:33 UTC, merged

2018-03-01 12:34 UTC, valorkin commented
@IlyaSurmay @EvilAlexei sample with custom validation has to be added anyway