docs(demos): decompose Simple accordion
valor-software/ng2-bootstrap pull request #3618
Opened 2018-02-01 13:42 UTC by olshansky

Decompose to Simple and With open event

close #3616

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-01 15:57 UTC, IlyaSurmay requested changes

2018-02-01 15:57 UTC, IlyaSurmay commented on demo/src/app/components/+accordion/accordion-section.list.ts
> +        description: `<p>Accordion with opening (<code>isOpenChange</code>) event listener.</p>`,
remove `opening`

2018-02-01 16:03 UTC, EvilAlexei requested changes
And where is demo with custom html?

2018-02-02 14:53 UTC, EvilAlexei requested changes
Rename `Simple accordion` to `Basic`

2018-02-02 14:53 UTC, EvilAlexei commented on demo/src/app/components/+accordion/accordion-section.list.ts
> +        description: `<p>Accordion with (<code>isOpenChange</code>) event listener.</p>`,
Remove brackets.

2018-02-02 14:53 UTC, EvilAlexei commented on demo/src/app/components/+accordion/accordion-section.list.ts
> +        title: 'With opening event',
Rename to Event isOpenChange

2018-02-02 15:13 UTC, EvilAlexei submitted a review, later dismissed

2018-02-02 15:31 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-05 15:39 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-06 16:48 UTC, valorkin commented on demo/src/app/components/+accordion/accordion-section.list.ts
> +        title: 'Event isOpenChange',
worst name ever :)

2018-02-06 16:49 UTC, valorkin requested changes

2018-02-06 16:49 UTC, valorkin commented on demo/src/app/components/+accordion/demos/custom-html/custom-html.html
> +  <accordion-group #group>
`#group` is not used and duplicated,
clean up things you don't need to have in demos
they should be simple and minimal
not confusing

2018-02-13 12:53 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-15 13:15 UTC, YevheniiaMazur commented
Tested. looks good

2018-02-23 12:30 UTC, valorkin approved these changes

2018-03-01 12:30 UTC, valorkin submitted a review, later dismissed

2018-03-01 12:31 UTC, merged