docs(demos): decompose Disabled
valor-software/ng2-bootstrap pull request #3620
Opened 2018-02-01 15:08 UTC by olshansky

close #3619

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-01 15:57 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-05 15:57 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-06 17:06 UTC, valorkin requested changes

2018-02-06 17:06 UTC, valorkin commented on demo/src/app/components/+accordion/demos/disabled/disabled.ts
>    status: any = {
why would you need object for only property?
please simplify

2018-02-06 17:06 UTC, valorkin commented on demo/src/app/components/+accordion/demos/opened/opened.ts
> +  status: any = {
same

2018-02-07 11:09 UTC, olshansky commented
@valorkin fixed :)

2018-02-07 13:37 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-13 11:43 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-15 13:35 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-23 12:29 UTC, merged