fix(alerts): after dismissing alert are not removing from DOM #3608
valor-software/ng2-bootstrap pull request #3622
Opened 2018-02-01 16:08 UTC by IraErshova

Fix removing alert from DOM after its dismissing

Close #3608

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated demos.

2018-02-08 14:26 UTC, IlyaSurmay requested changes

2018-02-08 14:26 UTC, IlyaSurmay commented on demo/src/app/components/+alerts/demos/dismiss-on-timeout/dismiss-on-timeout.html
> +  <alert [type]="alert.type" [dismissOnTimeout]="alert.timeout" (onClosed)="onClosed($event, alert)">{{ alert.msg }}</alert>
I'm sure you can use just `onClosed(alert)`

2018-02-08 14:26 UTC, IlyaSurmay commented on demo/src/app/components/+alerts/demos/dismiss/dismiss.html
> +  <alert [type]="alert.type" [dismissible]="dismissible" (onClosed)="onClosed($event, alert)">{{ alert.msg }}</alert>
same

2018-02-08 14:26 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/demos/async/async.ts
> +    { id: 3, name: 'Arizona', region: 'West' },
remove this file from commit

2018-02-08 15:22 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-09 11:45 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 15:43 UTC, valorkin commented on demo/src/app/components/+alerts/demos/dismiss-on-timeout/dismiss-on-timeout.ts
> +  onClosed(dismissedAlert: any): void {
type param

2018-02-22 15:43 UTC, valorkin commented on src/alert/alert.component.ts
> +import { OnChange } from '../utils';
this will break system.js

2018-02-22 15:43 UTC, valorkin commented on src/alert/alert.component.ts
> +import { OnChange } from '../utils';
please revert

2018-02-22 16:11 UTC, merged