fix(datepicker): add hide on scroll demo
valor-software/ng2-bootstrap pull request #3628
Opened 2018-02-02 10:21 UTC by tarusin

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-02 10:31 UTC, IlyaSurmay requested changes

2018-02-02 10:31 UTC, IlyaSurmay commented on demo/src/app/components/+datepicker/demos/hide-on-scroll/hide-on-scroll.ts
> +  @HostListener('window:scroll', ['$event'])
$event in redundant

2018-02-02 10:31 UTC, IlyaSurmay commented on demo/src/app/components/+datepicker/datepicker-section.list.ts
> +          <p>Hide datepicker when scroll.</p>
Hide the datepicker on page scroll.

2018-02-02 11:03 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-05 17:17 UTC, YevheniiaMazur commented
Got this error after unit tests run
![unittesterror](https://user-images.githubusercontent.com/27342505/35818588-27b1129a-0aa9-11e8-90a6-f3a0ffe9032b.jpg)

2018-02-05 19:46 UTC, EvilAlexei requested changes
No link to original issue (closes/fixes/related to)

2018-02-07 19:13 UTC, YevheniiaMazur commented
@tarusin , Please, fix conflicting files

2018-02-08 10:57 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-09 15:50 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-23 12:26 UTC, valorkin commented
@tarusin remove from demo sample all code and html which doesn't relate to demo

2018-02-23 14:20 UTC, valorkin approved these changes

2018-02-23 14:21 UTC, merged