docs(demos): decompose Dynamic accordion
valor-software/ng2-bootstrap pull request #3633
Opened 2018-02-02 12:32 UTC by olshansky

Decompose to: Dynamic accordion, Dynamic body content, Manual toggle

close #3627

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-02 13:18 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-05 17:33 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-06 17:08 UTC, valorkin requested changes

2018-02-06 17:08 UTC, valorkin commented on demo/src/app/components/+accordion/demos/manual-toggle/manual-toggle.ts
> +  status: any = {
object for one fild

2018-02-07 12:14 UTC, olshansky commented on demo/src/app/components/+accordion/demos/manual-toggle/manual-toggle.ts
> +  status: any = {
fixed

2018-02-07 13:36 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-13 13:27 UTC, IlyaSurmay requested changes

2018-02-13 13:27 UTC, IlyaSurmay commented on demo/src/app/components/+accordion/demos/dymanic/dynamic.ts
>    groups: any[] = [
remove type annotation

2018-02-13 13:27 UTC, IlyaSurmay commented on demo/src/app/components/+accordion/demos/dynamic-body/dynamic-body.ts
> +  items: string[] = ['Item 1', 'Item 2', 'Item 3'];
same
if type annotation isn't provided, typescript will use the type of the first assigned value

2018-02-13 13:37 UTC, IlyaSurmay approved these changes

2018-02-15 20:44 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 15:39 UTC, valorkin approved these changes

2018-02-22 15:39 UTC, merged