docs(tabs): make tabs content(tab-pane) looks nice #3642
valor-software/ng2-bootstrap pull request #3652
Opened 2018-02-05 12:01 UTC by IraErshova

Fill tabs demo with styled content

Close #3642

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated demos.

2018-02-05 12:14 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-05 19:51 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-06 17:16 UTC, valorkin requested changes
please remove `styles` usage in demos if not needed
by demo goal

2018-02-06 17:16 UTC, valorkin commented on demo/src/app/components/+tabs/demos/basic/basic.ts
> +  styles: ['.tab-container {padding: 10px 10px 0;}']
why do we need custom styles? 
is it intended part of demo?

2018-02-06 17:16 UTC, valorkin commented on demo/src/app/components/+tabs/demos/config/config.ts
> +  styles: ['.tab-container {padding: 10px 10px 0;}'],
try to avoid custom styles

2018-02-07 13:54 UTC, IlyaSurmay submitted a review, later dismissed

2018-03-01 15:02 UTC, valorkin approved these changes

2018-03-01 15:04 UTC, valorkin commented
it will be easier to redo than to resolve conflicts :)

2018-03-01 15:04 UTC, closed without merging