docs(typehead): rename demo Static array to Basic #3657
valor-software/ng2-bootstrap pull request #3658
Opened 2018-02-05 12:27 UTC by IraErshova

Rename demo Static array to Basic array

Close #3657

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-02-05 12:30 UTC, IlyaSurmay requested changes

2018-02-05 12:30 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/demos/basic/basic.ts
>    selector: 'demo-typeahead-static',
change selector name as well

2018-02-05 12:30 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/demos/basic/basic.ts
>  export class DemoTypeaheadStaticComponent {
and component name

2018-02-05 12:33 UTC, IlyaSurmay approved these changes

2018-02-22 15:17 UTC, valorkin approved these changes

2018-02-22 15:17 UTC, merged