docs(carousel): decomopose Dynamic Slides
valor-software/ng2-bootstrap pull request #3660
Opened 2018-02-05 12:47 UTC by olshansky

Decompose Dynamic Slides section to: Dynamic slides, Disable indicator, Disable slide looping, Interval

close #3651

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-05 14:06 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-05 20:28 UTC, YevheniiaMazur commented
Needs to fix interval demo - changing slides freezes for more than chosen timeout

2018-02-09 12:58 UTC, YevheniiaMazur commented
Discussed comment - need to recheck issue's reproducing

2018-02-09 13:19 UTC, YevheniiaMazur commented
Please, fix timeout for changing slides
![carouselinterval](https://user-images.githubusercontent.com/27342505/36029614-91fff476-0dac-11e8-8f57-fbd987f1296d.gif)

2018-02-12 14:26 UTC, olshansky commented
Interval work incorrect without `[(activeSlide)]`

2018-02-13 13:47 UTC, IlyaSurmay requested changes

2018-02-13 13:47 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/disable-looping/disable-looping.ts
> +  slides: any[] = [
remove type annotation

2018-02-13 13:47 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/disable-looping/disable-looping.ts
> +  noWrapSlides: boolean = false;
same

2018-02-13 13:47 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/dynamic/dynamic.ts
>    slides: any[] = [];
same

2018-02-13 13:47 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/interval/interval.ts
> +  myInterval: number = 1500;
:)

2018-02-13 14:49 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-16 11:51 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 14:48 UTC, merged