docs(typehead): add demo for typeaheadLatinize #3666
valor-software/ng2-bootstrap pull request #3671
Opened 2018-02-05 16:52 UTC by IraErshova

Add demo for typeaheadLatinize #3666

Close #3666

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-02-05 16:56 UTC, IlyaSurmay requested changes

2018-02-05 16:56 UTC, IlyaSurmay commented on src/typeahead/typeahead.directive.ts
> +  /** match latin symbols.
this would change the description for `typeaheadSingleWords`

2018-02-05 16:56 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/demos/index.ts
> +  wordDelimiters: {
I guess it's `latinize`, not `wordDelimiters`

2018-02-06 09:34 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-07 11:52 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-07 12:19 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 15:16 UTC, merged