keep invalid text in date input
valor-software/ng2-bootstrap pull request #3678
Opened 2018-02-06 08:22 UTC by arins

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [] added/updated tests.
 - [] added/updated API documentation.
 - [ ] added/updated demos.

2018-03-01 15:19 UTC, valorkin requested changes
I suppose it could be `keepInvalidValue` ?
Plus, please, apply same changes to date range picker
Thanks in advance

2018-03-01 15:19 UTC, valorkin commented on src/datepicker/bs-datepicker-input.directive.ts
> +			else
may be we shouldn't do anything here in else?

and please please format if:
```
if (..) {
////
}
```

2018-03-01 15:19 UTC, valorkin commented on src/datepicker/bs-datepicker-input.directive.ts
> +  public keepInvalidInputValue:boolean = false;
`@Input() keepInvalidInputValue = false;`

2018-03-01 15:19 UTC, valorkin commented
+ I suppose a separate demo for this use case is must :)

2019-04-17 09:07 UTC, ludmilanesvitiy commented
@arins Hello! Thank you for your contribution. As I see, a few changes requested to your PR, but they are not applied. Do you still need this PR?

2019-04-17 09:20 UTC, arins commented
I am not working in that project anymore so I don't know if it is needed. I personally don't need it but maybe someone else needs it. If you don't have use for it you can close the PR

2019-04-17 09:30 UTC, ludmilanesvitiy commented
@arins OK, Thank you.
Due to absent audience activity for the proposed change, I'll close this PR. If you need something similar - don't hesitate to create a new issue/PR.

2019-04-17 09:30 UTC, closed without merging

2019-05-02 15:32 UTC, szh commented
I have a need for this. Can this PR be re-opened?

2019-05-02 16:30 UTC, szh commented
Is there a workaround that works for now? I've tried adding a `bsValueChange` event listener as follows:
```
@ViewChild("dateInput") private dateInput: ElementRef;

private dateValChanged(val: Date): void {
    if (val instanceof Date && isNaN(val.getTime())) { // Invalid date
      // By default the input will show "Invalid Date", so manually set it to show the actual value
      setTimeout(() => this.renderer.setProperty(this.dateInput.nativeElement, 'value', this.field.Value), 0);
    }
  }
```
This appears to work when prefilling a field with an invalid date value, but not when manually entering it.

2019-09-24 19:05 UTC, charlesc32 commented
@szh I got your solution to work with 1 additional change. Unfortuenatly you have to keep track of the value as it changes. I added a handler for keyup and stored the value. Then check that value on (instead of valueChange) and reset the input value if its invalid. It seems to work ok so far.

onBlur() {
        if (isNaN((new Date(this.changedValue)).getTime())) { // Invalid date
            // By default the input will show "Invalid Date", so manually set it to show the actual value
            setTimeout(() => this.renderer.setProperty(this.dateInput.nativeElement, 'value', this.changedValue), 0);
          }
    }

    onKeyup($event) {
        if ($event.currentTarget.value.toLowerCase() !== 'invalid date') {
            this.changedValue = $event.currentTarget.value;
        }
    }