docs(carousel): add demo for activeSlideChange
valor-software/ng2-bootstrap pull request #3679
Opened 2018-02-06 09:28 UTC by olshansky

close #3677

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-06 10:27 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-07 12:54 UTC, YevheniiaMazur commented
Please, add more detailed description, how can I test this pr.

2018-02-07 13:26 UTC, YevheniiaMazur commented
Please, turn off slides' autochanging and make your demo more usefull (add output instead of console log)
Now, due to your solution too much logs appears:
![toomuch](https://user-images.githubusercontent.com/27342505/35918665-4ac74056-0c1b-11e8-90c9-0e6b275a2844.jpg)

2018-02-13 11:39 UTC, IlyaSurmay requested changes

2018-02-13 11:39 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/slide-changed-event/slide-changed-event.ts
> +  slideModel: string = '';
activeSlideChangeMessage or slideChangeMessage

2018-02-13 11:39 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/slide-changed-event/slide-changed-event.ts
> +  slideModel: string = '';
also, remove type annotation if a field has a default value

2018-02-13 11:39 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/slide-changed-event/slide-changed-event.ts
> +  slides: any[] = [
same

2018-02-13 11:50 UTC, IlyaSurmay approved these changes

2018-02-16 12:12 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 14:35 UTC, valorkin approved these changes

2018-02-22 14:35 UTC, merged