docs(typehead): add demo for typeaheadOnSelect output #3681
valor-software/ng2-bootstrap pull request #3685
Opened 2018-02-06 12:35 UTC by IraErshova

Add demo for typeaheadOnSelect output. To reproduce demo, please select one of the options and then you can see the selected option above the input ("Selected option"). [See screenshot ](http://joxi.ru/brRggRgHQZ9nam)

Close #3681

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-02-06 12:51 UTC, IlyaSurmay requested changes

2018-02-06 12:51 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +          <p>Fired when option was selected, return object with data of this option</p>
Fired when an option was selected, returns an object with this option.

2018-02-06 12:52 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +          <p>Fired when option was selected, return object with data of this option</p>
please change this in the jsdoc as well

2018-02-06 15:29 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-07 12:59 UTC, YevheniiaMazur commented
Please, provide more detailed description, how to test this pr (when this event calls, etc)

2018-02-09 13:33 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 14:30 UTC, valorkin requested changes

2018-02-22 14:30 UTC, valorkin commented on demo/src/app/components/+typeahead/demos/on-select/on-select.ts
> +  onSelect(event: any): void {
@IraErshova event type

2018-02-22 15:35 UTC, merged