docs(pagination): rename Default section to Basic and decompose
valor-software/ng2-bootstrap pull request #3687
Opened 2018-02-06 12:37 UTC by olshansky

close #3680

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-13 11:34 UTC, IlyaSurmay requested changes

2018-02-13 11:34 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/demos/disable-direction-links/disable-direction-links.html
> +<pagination [directionLinks]="false" [totalItems]="55"></pagination>
Demos like this one should have a button that toggles the part of the functionality that this demo shows.
`<button (click)="directionLinks = !directionLinks">azaza</button>`

2018-02-13 11:34 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/demos/disable-direction-links/disable-direction-links.ts
> +  selector: 'demo-pagination-disable-direction-links',
selector name `demo-pagination-disable-direction-links`
component name `DemoPaginationDirectionLinksComponent`
please be consistent in naming

2018-02-13 11:34 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/demos/page-changed-event/page-changed-event.ts
> +    console.log('Page changed to: ' + event.page);
get rid of `console.log` and show event data in `<pre>` or similar (like you do in `numPages` demo )

2018-02-13 12:34 UTC, IlyaSurmay requested changes

2018-02-13 12:34 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/demos/disable-boundary-links/disable-boundary-links.html
> +<pagination [boundaryLinks]="false" [totalItems]="55"></pagination>
add button that toggles `boundaryLinks`

2018-02-13 12:34 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/demos/disable-direction-links/disable-direction-links.ts
> +  templateUrl: './disable-direction-links.html'
since this demo shows disabled and enabled direction links, it's better to be named  just `direction links`

2018-02-13 12:34 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/demos/disable-boundary-links/disable-boundary-links.ts
> +  templateUrl: './disable-boundary-links.html'
check my comments for direction links demo and apply them to this demo as well

2018-02-13 13:16 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-16 12:33 UTC, YevheniiaMazur commented
For bootstrap 3 all buttons under pagination flows right (as on screenshot)
How it looks for bs3:
![bs3buttonflowsright](https://user-images.githubusercontent.com/27342505/36307756-3643c2e6-1326-11e8-91c1-5514a43ac748.jpg)

How it should look for both bs3 and 4:
![bs4buttonlooksgood](https://user-images.githubusercontent.com/27342505/36307772-497988aa-1326-11e8-9a13-b5076103521b.jpg)

2018-02-16 13:00 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-16 14:31 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 14:24 UTC, valorkin submitted a review, later dismissed

2018-02-22 14:26 UTC, merged