docs(typehead): add demo for typeaheadOnBlur output #3686
valor-software/ng2-bootstrap pull request #3689
Opened 2018-02-06 13:14 UTC by IraErshova

Add demo for typeaheadOnBlur output

Close #3686

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-02-06 13:29 UTC, IlyaSurmay requested changes

2018-02-06 13:29 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +         <p>Selects an option, on which user lost a focus. To reproduce start typing the name of the state, then focus
Returns an option on which user lost a focus. To reproduce start typing the name of the state, then focus on one of the options with mouse or arrow keys and click outside of the typeahead.

2018-02-06 15:02 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-07 13:10 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 14:20 UTC, valorkin submitted a review, later dismissed

2018-02-22 14:22 UTC, merged