docs(pagination): Add demo for disabled and active states
valor-software/ng2-bootstrap pull request #3692
Opened 2018-02-06 14:24 UTC by olshansky

Demo for swtitching disable state

close #3688

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-13 11:07 UTC, IlyaSurmay requested changes

2018-02-13 11:07 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/demos/index.ts
> +import { DemoPaginationStatesComponent } from './states/states';
`states` says nothing about disabled state. `DemoPaginationDisabledComponent` would be better

2018-02-13 11:07 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/demos/states/states.ts
> +  selector: 'demo-pagination-states',
same

2018-02-13 11:09 UTC, IlyaSurmay requested changes

2018-02-13 11:09 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/pagination-section.list.ts
> +        title: 'States',
`states` - > `disabled`

2018-02-13 11:09 UTC, IlyaSurmay commented on demo/src/app/components/+pagination/pagination-section.list.ts
> +        component: require('!!raw-loader?lang=typescript!./demos/states/states.ts'),
folder names as well

2018-02-13 11:20 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-16 13:22 UTC, YevheniiaMazur commented
For bootstrap 3 all buttons under pagination flows right (as on screenshot)
How it looks for bs3:
![bs3togglerbutton](https://user-images.githubusercontent.com/27342505/36309426-3459e396-132d-11e8-933f-fe9f85032b47.jpg)

Otherwise looks good

2018-02-16 13:44 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-16 15:08 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 14:16 UTC, valorkin submitted a review, later dismissed

2018-02-22 14:18 UTC, merged