docs(typehead): add demo for typeaheadNoResults output #3690
valor-software/ng2-bootstrap pull request #3693
Opened 2018-02-06 15:16 UTC by IraErshova

Add demo for typeaheadNoResults output. To see message "No Results Found" enter the value of which is not in the list

Close #3690

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-02-06 15:31 UTC, IlyaSurmay requested changes

2018-02-06 15:31 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +         "No Results Found" enter the value of which is not in the list</p>
enter the value of which is not in the list - > enter the value that doesn't match anything from the list

2018-02-08 14:31 UTC, IlyaSurmay requested changes

2018-02-08 14:31 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/demos/async/async.html
> +<div *ngIf="typeaheadLoading===true">Loading</div>
`*ngIf="typeaheadLoading"` ?

2018-02-08 16:30 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-09 13:52 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 14:03 UTC, valorkin requested changes

2018-02-22 14:03 UTC, valorkin commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +         <p>Fired on every key event and returns true in case of matches are not detected. To see message
seriously? you are writing this for humans

2018-02-22 14:49 UTC, valorkin approved these changes

2018-02-22 14:49 UTC, merged