docs(carousel): add demo with noPause function
valor-software/ng2-bootstrap pull request #3708
Opened 2018-02-07 11:32 UTC by tarusin

add demo with toggle pause on hover button
close #3645

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-07 12:23 UTC, IlyaSurmay requested changes

2018-02-07 12:23 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/carousel-section.list.ts
> +        title: 'No Pause Slides',
Pause on hover

2018-02-07 12:23 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/no-pause/no-pause.html
> +          (click)="noPauseSlide()">Toggle pause on hover
no need for a function, change the binding here

2018-02-07 12:23 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/no-pause/no-pause.ts
> +  noPauseSlide() {
remove this

2018-02-07 13:14 UTC, IlyaSurmay requested changes

2018-02-07 13:14 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/no-pause/no-pause.html
> +          (click)="this.noPauseSlides = !this.noPauseSlides">Toggle pause on hover
remove `this`

2018-02-07 13:14 UTC, IlyaSurmay commented on demo/src/app/components/+carousel/demos/no-pause/no-pause.ts
> +  showIndicator = true;
why do you need all these properties? leave only  `noPauseSlides` and rename it to `noPause`

2018-02-07 13:27 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-08 15:00 UTC, YevheniiaMazur commented
Please, update your pr from latest dev and fix e2e tests, if they continue fails

2018-02-13 13:51 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-16 13:35 UTC, YevheniiaMazur commented
Very hard to test and to see difference, please, set interval for slide changing smaller

2018-02-16 13:35 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 14:00 UTC, valorkin commented on demo/src/app/components/+carousel/carousel-section.list.ts
> +NgApiDocComponent,
code formatting!

2018-02-22 14:00 UTC, valorkin commented on demo/src/app/components/+carousel/carousel-section.list.ts
> +        html: require('!!raw-loader?lang=markup!./demos/no-pause/no-pause.html'),
demo description

2018-02-22 15:53 UTC, valorkin approved these changes

2018-02-22 15:54 UTC, merged