fix(dropdown): fix dropdown inside click
valor-software/ng2-bootstrap pull request #3738
Opened 2018-02-09 13:44 UTC by IlyaSurmay

Fixes #1933 

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

2018-02-28 16:27 UTC, daddykotex commented
Hi, 

IMO this is a very nice feature. Do you need any help for this? I'm willing to help to get this merged!

Thanks to @IlyaSurmay

2018-02-28 16:48 UTC, valorkin commented
I am slowly getting there
~50 PRs already merged, 50 to go :D

2018-02-28 17:02 UTC, daddykotex commented
Oh ok, no issue, If I can do anything, let me know

2018-03-01 15:41 UTC, valorkin requested changes
don't make _elRefs public
add `_contains` method and mark it as `@internal` in jsdoc

2018-03-01 15:41 UTC, valorkin commented on src/dropdown/bs-dropdown-container.component.ts
> +    public _element: ElementRef
`public`?

2018-03-01 15:41 UTC, valorkin commented on src/dropdown/bs-dropdown-toggle.directive.ts
> +    if (this._state.autoClose && event.button !== 2 && !this._element.nativeElement.contains(event.target)) {
both if's inside do the same thing?

2018-03-01 15:41 UTC, valorkin commented on src/dropdown/bs-dropdown.directive.ts
> +  constructor(public _elementRef: ElementRef,
why public?

2019-01-04 10:42 UTC, Domainv commented
Close to prefer #4609

2019-01-04 10:42 UTC, closed without merging