docs(typehead): add demo for using with forms #3748
valor-software/ng2-bootstrap pull request #3750
Opened 2018-02-12 11:27 UTC by IraErshova

Add demo for using with template-driven forms

Close #3748

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-02-13 11:55 UTC, IlyaSurmay requested changes

2018-02-13 11:55 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/demos/reactive-form/reactive-form.ts
>    stateCtrl: FormControl = new FormControl();
remove type annotations if a field has a default value

2018-02-13 13:14 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-16 13:50 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 13:47 UTC, valorkin requested changes

2018-02-22 13:47 UTC, valorkin commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +          <p>Typeahead can be used in reactive forms. Keep in mind that value of <code>ngModel</code> is string</p>
reactive forms doesn't use ngModel

2018-02-22 13:47 UTC, valorkin commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +          <p>Typeahead can be used in reactive forms. Keep in mind that value of <code>ngModel</code> is string</p>
please change wording

2018-02-22 14:34 UTC, valorkin approved these changes

2018-02-22 14:34 UTC, merged