docs(collapse): decompose Basic demo
valor-software/ng2-bootstrap pull request #3792
Opened 2018-02-15 13:48 UTC by olshansky

close #3789

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-23 14:47 UTC, IlyaSurmay requested changes

2018-02-23 14:47 UTC, IlyaSurmay commented on demo/src/app/components/+collapse/collapse-section.list.ts
> +        title: 'Collapsed & expanded events listening',
just `Events`

2018-02-23 14:47 UTC, IlyaSurmay commented on demo/src/app/components/+collapse/collapse-section.list.ts
> +        outlet: CollapseDemoEventsComponent
add a description field with text `Collapse directive exposes 2 events: <code>collapsed</code>, that fires when a content was hidden, and  <code>expanded</code>, that fires when a content was shown`

2018-02-23 15:12 UTC, IlyaSurmay approved these changes

2018-03-13 12:12 UTC, valorkin approved these changes

2018-03-13 16:17 UTC, YevheniiaMazur commented
Needs to fix conflicts

2018-03-13 16:29 UTC, closed without merging

2018-03-13 16:31 UTC, valorkin commented
@olshansky why close PR and delete branch?

2018-03-13 16:37 UTC, olshansky commented
@valorkin mistake 
open same pr #3977