docs(popover): add isOpen input demo
valor-software/ng2-bootstrap pull request #3806
Opened 2018-02-16 08:24 UTC by tarusin

add demo with isOpen input
closes #3795

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated demos.

2018-02-16 10:28 UTC, IlyaSurmay requested changes

2018-02-16 10:28 UTC, IlyaSurmay commented on demo/src/app/components/+popover/demos/toggle-manual/toggle-manual.html
> +        (click)="isOpen = !isOpen"
what's the point? you're changing `isOpen` but you're not using it as popover's input

use `triggers=""` and `[isOpen]="isOpen"` and toggle `isOpen` by separete button

2018-02-16 10:28 UTC, IlyaSurmay commented on demo/src/app/components/+popover/demos/toggle-manual/toggle-manual.ts
> +export class DemoPopoverToggleManualComponent {
change the name to `DemoPopoverTriggerByInput` (and selector, filenames and folder name as well)

2018-02-16 11:22 UTC, IlyaSurmay approved these changes

2018-02-20 11:35 UTC, YevheniiaMazur commented
Please, add more information, what's the difference between this demo and other demos. And not clear, why "trigger input", when we call isOpen property by button click

2018-02-20 12:20 UTC, tarusin commented
i call this demo "trigger by input" because when we click button the popover trigger by input.

2018-02-20 12:35 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 11:48 UTC, valorkin approved these changes

2018-02-22 11:49 UTC, merged