docs(popover): add onShown & onHidden output demo
valor-software/ng2-bootstrap pull request #3810
Opened 2018-02-16 12:11 UTC by olshansky

Add demo for showing and hiding events

close #3807

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-16 12:24 UTC, IlyaSurmay requested changes

2018-02-16 12:24 UTC, IlyaSurmay commented on demo/src/app/components/+popover/popover-section.list.ts
> +        title: 'Showing/Hiding events listeners',
just `Visibility events`

2018-02-16 12:36 UTC, olshansky commented on demo/src/app/components/+popover/popover-section.list.ts
> +        title: 'Showing/Hiding events listeners',
@IlyaSurmay thx, couldn't find a good title

2018-02-16 12:37 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-20 11:50 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-20 11:51 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 11:45 UTC, valorkin submitted a review, later dismissed

2018-02-22 11:59 UTC, merged