docs(popover): add popoverContext input demo
valor-software/ng2-bootstrap pull request #3819
Opened 2018-02-16 15:02 UTC by tarusin

Add demo where context will be used if popover is a template
Closes #3808

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-16 15:14 UTC, IlyaSurmay requested changes

2018-02-16 15:14 UTC, IlyaSurmay commented on demo/src/app/components/+popover/demos/popover-context/popover-context.html
> +<ng-template #popTemplate let-contextMessageLocal="contextMessage">{{ contextMessageLocal }}</ng-template>
that's too long 
` let-contextMessageLocal` -> ` let-message`

2018-02-16 15:14 UTC, IlyaSurmay commented on demo/src/app/components/+popover/demos/popover-context/popover-context.ts
> +    contextMessage: 'Hello there!'
just `message`

2018-02-16 15:27 UTC, IlyaSurmay approved these changes

2018-02-16 15:27 UTC, IlyaSurmay requested changes

2018-02-16 15:27 UTC, IlyaSurmay commented on demo/src/app/components/+popover/demos/popover-context/popover-context.html
> +  Toggle context
Open popover with custom context

2018-02-16 15:33 UTC, IlyaSurmay approved these changes

2018-02-20 13:24 UTC, YevheniiaMazur commented
Not clear, why this demo called input demo, only template content displayed there. @tarusin ,please, clarify this moment
![whyinput](https://user-images.githubusercontent.com/27342505/36426194-00ea438e-1652-11e8-9d4e-54a33443dec6.jpg)

2018-02-20 13:30 UTC, YevheniiaMazur commented
Clarified, looks good

2018-02-22 11:34 UTC, valorkin approved these changes

2018-02-22 11:34 UTC, merged