docs(sortable): rename string item to basic
valor-software/ng2-bootstrap pull request #3829
Opened 2018-02-19 09:42 UTC by tarusin

Rename string items demo to basic

Closes #3824

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-19 10:33 UTC, IlyaSurmay requested changes

2018-02-19 10:33 UTC, IlyaSurmay commented on demo/src/app/components/+sortable/demos/basic/basic.component.ts
>    itemStringsLeft: any[] = [
remove type annotation

2018-02-19 10:57 UTC, IlyaSurmay approved these changes

2018-02-20 14:20 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 11:29 UTC, merged