docs(popover): add more complicated(new) example for Custom triggers demo
valor-software/ng2-bootstrap pull request #3831
Opened 2018-02-19 10:31 UTC by olshansky

Add Double click event and Input change event triggers exaples

Close #3828

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-19 10:43 UTC, IlyaSurmay requested changes

2018-02-19 10:43 UTC, IlyaSurmay commented on demo/src/app/components/+popover/demos/triggers-custom/triggers-custom.html
> +           placeholder="Show popover on input changing"
changing - > change

2018-02-19 10:45 UTC, IlyaSurmay approved these changes

2018-02-20 14:42 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 11:29 UTC, merged