docs(popover): fix Append to body demo
valor-software/ng2-bootstrap pull request #3844
Opened 2018-02-20 09:21 UTC by tarusin

Fix html markup for bs4, for bs4 make more visible the problem with default popover.

Closes #3837

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.

2018-02-20 10:35 UTC, IlyaSurmay requested changes

2018-02-20 10:35 UTC, IlyaSurmay commented on demo/src/assets/css/bootstrap-4.0.0/css/bootstrap.min.css
>   */:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gr
don't change bootstrap styles

2018-02-20 11:25 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-20 15:49 UTC, YevheniiaMazur commented
Needs fix - haven't seen this commit after pulling pr for check

2018-02-21 10:51 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-21 12:25 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 11:25 UTC, merged