docs(typehead): add demo for typeaheadSingleWords
valor-software/ng2-bootstrap pull request #3846
Opened 2018-02-20 10:33 UTC by olshansky

If typeaheadSingleWords=true ignores spaces and seeking for matches with occurrences of entered words.
For example:
- Ari zona -> Arizona
- A l a b a m a -> Alabama

Close #3843

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-20 11:24 UTC, IlyaSurmay requested changes

2018-02-20 11:24 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/demos/single-world/single-world.ts
> +  states: string[] = [
remove type annotation

2018-02-20 11:24 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +        description: `If <code>typeaheadSingleWords=true</code> ignores spaces and seeking for matches with occurrences of entered words.`,
add example (the one from PR description would fit)

2018-02-20 11:33 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-21 12:45 UTC, YevheniiaMazur commented
As this parameter ignores not only spaces, but order too, will be better rename demo to "Ignore spaces and order", or something like that
As you can see at screenshot, zona Ari -> Arizona
![notcorrectname](https://user-images.githubusercontent.com/27342505/36480657-c6ef7c3e-1715-11e8-8be1-06c9289dea58.jpg)

2018-02-21 13:01 UTC, IlyaSurmay submitted a review, later dismissed

2018-02-21 13:39 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 11:22 UTC, valorkin submitted a review, later dismissed

2018-02-22 12:42 UTC, merged