docs(typehead): add demo for typeaheadPhraseDelimiters
valor-software/ng2-bootstrap pull request #3848
Opened 2018-02-20 12:39 UTC by olshansky

Sets the word delimiter to match exact phrase (you can divide keywords by typeaheadPhraseDelimiters)

Close #3847

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated demos.

2018-02-20 12:54 UTC, IlyaSurmay requested changes

2018-02-20 12:54 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/demos/phrase-delimiters/phrase-delimiters.html
> +       [typeaheadPhraseDelimiters]="'&,'"
if you bind a simple string, use this kind of binding `typeaheadPhraseDelimiters="&,"`

2018-02-20 13:03 UTC, IlyaSurmay approved these changes

2018-02-21 14:16 UTC, YevheniiaMazur commented
Tested, looks good

2018-02-22 11:21 UTC, valorkin approved these changes

2018-02-22 11:21 UTC, merged