feat(datepicker): Add directive for inline datepicker
valor-software/ng2-bootstrap pull request #3956
Opened 2018-03-08 10:48 UTC by martintro

Closes valor-software/ngx-bootstrap#3955

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

2018-03-15 11:25 UTC, alexborghesi submitted a review, later dismissed
looks good

2018-03-16 16:20 UTC, martintro commented
Closes valor-software/ngx-bootstrap#3958

2018-03-21 08:38 UTC, amorenew commented
@martintro I wonder if you could small sample how could we use this inline datepicker?
Thanks

2018-03-21 08:46 UTC, martintro commented
@amorenew Please have a look at the demo files in the PR for example.
It’s like <bs-datepicker-inline></bs-datepicker-inline>

2018-03-21 08:52 UTC, amorenew commented
@martintro Yeah I saw it nice
`<bs-datepicker-inline></bs-datepicker-inline>`
well done 👍 
I have a small suggestion I think it could be nicer to be `<bs-datepicker></bs-datepicker>`

2018-03-25 11:03 UTC, shyamal890 commented
Can another reviewer please review and merge this pull request to the main repo.

2018-05-03 13:27 UTC, valorkin commented
@martintro LGTM!

2018-06-13 11:38 UTC, ishworthapaliya commented
Any update on this one?

2018-06-13 11:57 UTC, martintro commented
@ishworthapaliya I hope so soon. I'm waiting for approval :)

2018-07-03 14:03 UTC, x1unix commented
@valorkin, please review this PR.

2018-07-11 16:59 UTC, pmramos commented
Could really use this!

2018-12-13 09:27 UTC, ludmilanesvitiy commented on demo/src/app/components/+datepicker/demos/inline-datepicker/inline-datepicker.component.html
> +<p>with initial state set by <code>bsInlineValue</code> property</p>
Not need to add description to the DEMO inside the template for component, better will be move it as a description inside `datepicker-section.list.ts`

2018-12-13 12:10 UTC, Domainv commented on demo/src/app/components/+datepicker/demos/inline-datepicker/inline-datepicker.component.html
> +<p>with initial state set by <code>bsInlineValue</code> property</p>
fixed

2018-12-13 14:53 UTC, Domainv submitted a review, later dismissed

2019-01-11 11:55 UTC, ludmilanesvitiy submitted a review, later dismissed

2019-01-16 09:30 UTC, martintro commented
When will this be merged?

2019-01-18 09:50 UTC, Domainv submitted a review, later dismissed

2019-01-18 15:38 UTC, valorkin requested changes
please fix imports and ready for merge

2019-01-18 15:38 UTC, valorkin commented on src/index.ts
> +import { AccordionModule } from './accordion';
this type of import usually kills system js builds

2019-01-18 15:38 UTC, valorkin commented on src/index.ts
> +import { AccordionModule } from './accordion';
@Domainv this is why I didn't yet merged

2019-01-18 17:01 UTC, Domainv commented on src/index.ts
> +import { AccordionModule } from './accordion';
fixed

2019-01-18 17:14 UTC, valorkin approved these changes
Thanks!

2019-01-18 17:15 UTC, merged