tab can close datpicker, esc can exit datpicker
valor-software/ng2-bootstrap pull request #3966
Opened 2018-03-11 18:41 UTC by 5earle

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-03-11 19:21 UTC, 5earle commented
Addresses #3889 
Addresses #3890

2018-03-29 10:37 UTC, valorkin requested changes
Hey, thanks for PR!
I think we could merge close on ESC
but not sure about tab related logic

if you could split this PR into 2 (one with ESC one with Tab, logic) it would be easier to merge

2018-03-29 10:37 UTC, valorkin commented on src/component-loader/component-loader.class.ts
> +      setTimeout(() => {
why setTimeout is required?

2018-12-13 09:35 UTC, Domainv commented
'tab can close datepicker' functionality was cut out as unnecessary for now

2018-12-13 11:59 UTC, Domainv submitted a review, later dismissed

2018-12-13 12:08 UTC, ludmilanesvitiy commented
Smoke tested in Chrome, FF  -Esc always close the Datepicker. Looks good.

2018-12-13 17:13 UTC, valorkin approved these changes
LGTM, thanks ;)

2018-12-13 17:14 UTC, merged