docs(rating): add key nav support
valor-software/ng2-bootstrap pull request #4026
Opened 2018-03-19 12:30 UTC by tarusin

Added demo with feature where after press `enter` key the arrow keys are disabled

Closes #4018

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

2018-03-19 14:21 UTC, IlyaSurmay requested changes

2018-03-19 14:21 UTC, IlyaSurmay commented on demo/src/app/components/+rating/demos/select-on-enter/select-on-enter.ts
> +  onKeyup(event) {
type?

2018-03-19 14:21 UTC, IlyaSurmay commented on demo/src/app/components/+rating/demos/select-on-enter/select-on-enter.html
> +  <pre class="card-block card-header" style="margin:15px 0;">Rate: <b>{{rate}}</b>;  Readonly is: <i>{{isReadonly}}</i>;</pre>
Rate -> Rating (or Value)

2018-03-19 14:21 UTC, IlyaSurmay commented on demo/src/app/components/+rating/demos/select-on-enter/select-on-enter.ts
> +      this.isReadonly = !this.isReadonly;
I might be wrong but it seems like in this case user will be able to change the value again just by pressing `Enter` again

2018-03-19 14:21 UTC, IlyaSurmay commented on demo/src/app/components/+rating/rating-section.list.ts
> +        description: 'Use this example for accessibility. After press Enter key the arrow keys are disabled.',
please change the description because readonly datepicker disables all types of interaction, not only arrow keys

2018-03-19 15:59 UTC, IlyaSurmay requested changes

2018-03-19 15:59 UTC, IlyaSurmay commented on demo/src/app/components/+rating/rating-section.list.ts
> +        description: 'Use this example for accessibility. After press Enter key all types of interaction are disabled.',
what types of interactions? point them out explicitly (arrow keys and click)

2018-03-19 15:59 UTC, IlyaSurmay commented on demo/src/app/components/+rating/demos/select-on-enter/select-on-enter.html
> +  <pre class="card-block card-header" style="margin:15px 0;">Rating: <b>{{rate}}</b>;  Readonly is: <i>{{isReadonly}}</i>;</pre>
add a button that resets rating and readonly status

2018-03-22 11:15 UTC, IlyaSurmay requested changes

2018-03-22 11:15 UTC, IlyaSurmay commented on demo/src/app/components/+rating/demos/select-on-enter/select-on-enter.html
> +        [titles]="['one','two','three']" (keyup)="confirmSelection($event)" (onLeave)="overStar = 0"></rating>
why do you need  `overStar` if it's not used anywhere else?

2018-03-22 11:15 UTC, IlyaSurmay commented on demo/src/app/components/+rating/demos/select-on-enter/select-on-enter.html
> +<button class="btn btn-primary" (keyup)="resetStars($event)">Reset rating and status</button>
does this button do anything on click?

2018-03-22 12:31 UTC, IlyaSurmay requested changes

2018-03-22 12:31 UTC, IlyaSurmay commented on demo/src/app/components/+rating/rating-section.list.ts
> +        description: `Use this example for accessibility. After press <code>Enter</code>
Key navigation example. Focus on rating and use arrow keys to set its value, then press `Enter` to select the value, after this, the rating state will be changed to readonly.

2018-03-30 16:00 UTC, IlyaSurmay approved these changes

2018-04-02 11:15 UTC, YevheniiaMazur commented
@tarusin ,description in PR is not the same, then in issue. In issue: selecting rating by keys, in PR: only disabling arrow keys by pressing `enter` key. Please, tell, which one is correct?

2018-04-02 12:39 UTC, YevheniiaMazur commented
Tested, looks good

2018-04-05 12:11 UTC, merged