docs(tabs): add keyboard navigation
valor-software/ng2-bootstrap pull request #4050
Opened 2018-03-21 14:13 UTC by tarusin

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated API documentation.

2018-03-30 15:56 UTC, IlyaSurmay requested changes

2018-03-30 15:56 UTC, IlyaSurmay commented on src/tabs/tabset.component.ts
> +  @Input() removable: boolean;
this input is never used, also why anyone would need to remove tabset?

2018-04-04 14:17 UTC, IlyaSurmay approved these changes

2018-04-06 12:46 UTC, YevheniiaMazur commented
@tarusin , please, add link to github issue, that linked with this PR, or provide more information, how to test this PR (what keys are used for navigation, where key navigation was added, etc.)

2019-06-19 13:41 UTC, Domainv commented
Closing to favor #5284

2019-06-19 13:41 UTC, closed without merging