docs(buttons): add aria-attributes
valor-software/ng2-bootstrap pull request #4082
Opened 2018-03-23 15:57 UTC by tarusin

Closes #4068

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

2018-03-30 16:14 UTC, IlyaSurmay requested changes

2018-03-30 16:14 UTC, IlyaSurmay commented on src/buttons/button-checkbox.directive.ts
> +  @Input() btnCheckboxTrue = true;
`any` must be there because we need the ability to set other values as possible values of the button.

2018-03-30 16:14 UTC, IlyaSurmay commented on demo/src/app/components/+buttons/demos/disabled/disabled.html
> +<button type="button" class="btn btn-warning" (click)="isDisabled()" [attr.aria-pressed]="isPressed">Enable/Disable</button>
remove `disabled` demo from this PR, probably `disabled` demo will be deleted

2018-04-04 14:19 UTC, IlyaSurmay requested changes

2018-04-04 14:19 UTC, IlyaSurmay commented on demo/src/app/components/+buttons/demos/disabled/disabled.ts
> -import { Component } from '@angular/core';
I asked to remove disabled demo from this PR, not from the project itself :)

2018-04-05 12:51 UTC, IlyaSurmay approved these changes

2018-04-06 14:44 UTC, YevheniiaMazur commented
Not all described in linked issue aria-attributes were added (aria-disabled wasn't)
Issue description:
![issuedescr](https://user-images.githubusercontent.com/27342505/38427516-1982b8b6-39c2-11e8-9a79-13a17b5b3da5.jpg)
Demo with button, that can be disabled:
![disabledemo](https://user-images.githubusercontent.com/27342505/38427560-3448131c-39c2-11e8-9c67-6c824587f43f.jpg)

2018-04-25 14:58 UTC, valorkin approved these changes

2018-04-25 14:59 UTC, merged