docs(collapse): add aria-attributes
valor-software/ng2-bootstrap pull request #4095
Opened 2018-03-26 11:04 UTC by tarusin

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

2018-03-30 15:19 UTC, IlyaSurmay approved these changes

2018-03-30 15:28 UTC, IlyaSurmay requested changes

2018-03-30 15:28 UTC, IlyaSurmay commented on src/collapse/collapse.directive.ts
> -  @HostBinding('attr.aria-expanded')
this breaks tests for collapse module, fix the tests

2018-04-05 09:53 UTC, IlyaSurmay requested changes
`@HostBinding('attr.aria-expanded')` in `collapse.directive.ts`
remove this and fix the tests

2018-04-24 12:46 UTC, valorkin approved these changes

2018-04-24 12:46 UTC, merged