docs(dropdown): decompose manual triggering demo
valor-software/ng2-bootstrap pull request #4116
Opened 2018-03-27 12:02 UTC by YevheniiaMazur

# PR Checklist
 - [ ] built and tested the changes locally.
 - [ ] updated API documentation.
 - [ ] updated demos.

Closes: https://github.com/valor-software/ngx-bootstrap/issues/4110
What was done:
- [ ] demo was decomposed into two parts:
![2partsoftrgg](https://user-images.githubusercontent.com/27342505/37965916-73609376-31cf-11e8-9e96-8985f2b142ee.jpg)
- [ ] was used direct change of `isOpen` property instead of creating special method for it:
![directchange](https://user-images.githubusercontent.com/27342505/37965966-9615924a-31cf-11e8-9832-06b03460e6be.jpg)
- [ ] API documentation was updated:
![apidoc](https://user-images.githubusercontent.com/27342505/37965998-b4964e12-31cf-11e8-9355-cc5c63977e7a.jpg)

2018-04-05 11:43 UTC, IlyaSurmay requested changes

2018-04-05 11:43 UTC, IlyaSurmay commented on demo/src/app/components/+dropdown/demos/trigger-by-isopen-property/trigger-by-isopen-property.html
> +<button type="button" class="btn btn-primary" (click)="dropdown.isOpen=!dropdown.isOpen">Toggle</button>
`dropdown.isOpen = !dropdown.isOpen`

2018-04-05 11:43 UTC, IlyaSurmay commented on demo/src/app/components/+dropdown/dropdown-section.list.ts
> +          Use method <code>toggle(true)</code> if you want create toggler, or <code>toggle(false)</code>
if you want create toggler -> if you want to toggle the dropdown

2018-04-05 11:43 UTC, IlyaSurmay commented on demo/src/app/components/+dropdown/dropdown-section.list.ts
> +          if you want only close opened dropdown.
if you want only close opened dropdown -> if you only want to close the dropdown

2018-04-05 11:43 UTC, IlyaSurmay commented on demo/src/app/components/+dropdown/dropdown-section.list.ts
> +        description: `<p>Dropdown can be shown or hidden by direct change of <code>isOpen</code> input property</p>`,
by direct change of -> by changing

2018-04-05 11:43 UTC, IlyaSurmay commented on demo/src/ng-api-doc.ts
> +        "description": "<p>Toggles an element’s popover. This is considered a “manual” triggering of\nthe popover. With parameter true allow toggling, with parameter false\nonly hide opened dropdown.
allow -> allows
hide -> hides
also put `true` in `<code></code>`
3rd ngx bootstrap release  -  ngx-bootstrap v3

2018-04-05 14:14 UTC, IlyaSurmay requested changes

2018-04-05 14:14 UTC, IlyaSurmay commented on demo/src/app/components/+dropdown/dropdown-section.list.ts
> +        description: `<p>Dropdown can be shown or hidden by changing of <code>isOpen</code> input property</p>`,
changing of -> changing

2018-04-05 14:16 UTC, IlyaSurmay approved these changes

2018-04-10 09:17 UTC, YevheniiaMazur commented
Tested, looks good

2018-04-24 11:36 UTC, valorkin approved these changes

2018-04-24 14:31 UTC, merged