feat(modals): add aria-attributes
valor-software/ng2-bootstrap pull request #4117
Opened 2018-03-27 12:04 UTC by tarusin

Closes #4114

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated API documentation.
 - [x] added/updated demos.

2018-03-30 15:13 UTC, IlyaSurmay requested changes

2018-03-30 15:13 UTC, IlyaSurmay commented on src/modal/modal-container.component.ts
> +    <div [class]="'modal-dialog' + (config.class ? ' ' + config.class : '')">
why did you remove `role="document"?` original bootstrap' modal has it https://getbootstrap.com/docs/4.0/components/modal/#modal-components

2018-03-30 15:13 UTC, IlyaSurmay commented on demo/src/app/components/+modal/demos/auto-shown/auto-shown.html
> +     tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="dialog-auto-name" aria-modal="true">
aria-hidden attribute has to be removed or changed to `false` when the modal is opened

2018-03-30 15:13 UTC, IlyaSurmay commented on demo/src/app/components/+modal/demos/auto-shown/auto-shown.html
> +     tabindex="-1" role="dialog" aria-hidden="true" aria-labelledby="dialog-auto-name" aria-modal="true">
this is for all the demos you've changed in this PR

2018-04-02 11:50 UTC, IlyaSurmay requested changes

2018-04-02 11:50 UTC, IlyaSurmay commented on demo/src/app/components/+modal/demos/auto-shown/auto-shown.html
> +     tabindex="-1" role="dialog" aria-labelledby="dialog-auto-name" aria-modal="true">
use renderer to append `aria-modal` attribute

2018-04-02 12:44 UTC, IlyaSurmay approved these changes

2018-04-02 14:34 UTC, YevheniiaMazur commented
No modal has tag `aria-labelledby`, but example has.
Demo ngx bootstrap in this PR:
![noarialabel](https://user-images.githubusercontent.com/27342505/38200174-033a1186-369c-11e8-8292-aee1838d2c42.jpg)

Example demo:
![labelledby](https://user-images.githubusercontent.com/27342505/38200169-fe821a30-369b-11e8-8213-15619dc461bd.jpg)

2018-04-02 16:31 UTC, YevheniiaMazur commented
Tested, looks good

2018-04-05 12:17 UTC, valorkin approved these changes

2018-04-05 12:17 UTC, merged