feat(carousel): add aria-attributes
valor-software/ng2-bootstrap pull request #4131
Opened 2018-03-28 13:41 UTC by tarusin

Closes #4130

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated API documentation.

2018-03-30 14:29 UTC, IlyaSurmay requested changes

2018-03-30 14:29 UTC, IlyaSurmay commented on src/carousel/slide.component.ts
> +  @HostBinding('attr.aria-hidden')
when the slide is active, `aria-hidden` will be set to `true`, which doesn't seem like a correct behavior.

2018-04-02 10:04 UTC, IlyaSurmay requested changes

2018-04-02 10:04 UTC, IlyaSurmay commented on src/carousel/slide.component.ts
> +    '[attr.aria-hidden]': 'active ? false : true'
`'[attr.aria-hidden]': '!active'`

2018-04-02 10:33 UTC, IlyaSurmay approved these changes

2018-04-02 13:19 UTC, YevheniiaMazur commented
Tested, looks good

2018-04-05 12:19 UTC, merged