docs(tabs): update titles and descriptions at demo page
valor-software/ng2-bootstrap pull request #4133
Opened 2018-03-28 14:01 UTC by YevheniiaMazur

# PR Checklist
 - [ ] built and tested the changes locally.
 - [ ] updated demos.

Closes: https://github.com/valor-software/ngx-bootstrap/issues/4128

What was done (changes are highlighted on screenshots):
- updated `Manual selection` demo:
![manualselupd](https://user-images.githubusercontent.com/27342505/38033686-3b876440-32a9-11e8-882e-84b12673d2f0.jpg)

- updated `Disable selection` demo:
![disabledtabupd](https://user-images.githubusercontent.com/27342505/38033721-54ab49c8-32a9-11e8-89d6-9270f82d92db.jpg)

- updated `Dynamic tabs` demo:
![dynamictabsupd](https://user-images.githubusercontent.com/27342505/38033771-70fbc7a6-32a9-11e8-9da7-4c05f3ae2bcb.jpg)

- updated `Styling` demo:
![customclass](https://user-images.githubusercontent.com/27342505/38033808-8b79c34e-32a9-11e8-9cd3-5cc326443e5f.jpg)

2018-04-05 11:27 UTC, IlyaSurmay requested changes

2018-04-05 11:27 UTC, IlyaSurmay commented on demo/src/app/components/+tabs/demos/index.ts
> +  DemoTabsDisabledComponent,
remove duplicate

2018-04-05 15:01 UTC, IlyaSurmay approved these changes

2018-04-24 12:43 UTC, valorkin approved these changes

2018-04-24 12:43 UTC, merged