docs(timepicker): update titles and descriptions for demos
valor-software/ng2-bootstrap pull request #4142
Opened 2018-03-29 12:32 UTC by YevheniiaMazur

# PR Checklist
 - [ ] built and tested the changes locally.
 - [ ] updated demos.

Closes https://github.com/valor-software/ngx-bootstrap/issues/4140

Changes are highlighted on screenshots:
- `Custom meridian` demo: description was added:
![custommerupd](https://user-images.githubusercontent.com/27342505/38088842-f682d290-3365-11e8-9b01-dc1957c95576.jpg)
- `Custom validation`: was added one more condition for applying alert type:
![customvalidupd](https://user-images.githubusercontent.com/27342505/38088878-22b4cd6e-3366-11e8-80dc-5c2b9f43ea79.jpg)
- `IsValid` demo: title and description were updated:
![isvalidupd](https://user-images.githubusercontent.com/27342505/38088913-4729a174-3366-11e8-8835-fccd5b50b1ad.jpg)

2018-04-05 11:22 UTC, IlyaSurmay requested changes

2018-04-05 11:22 UTC, IlyaSurmay commented on demo/src/app/components/+timepicker/timepicker-section.list.ts
> +        title: 'Event validation',
it's better to replace it with `Custom validation with isValid event` :)

2018-04-06 11:30 UTC, IlyaSurmay approved these changes

2018-04-10 10:18 UTC, YevheniiaMazur commented
Tested, looks good

2018-04-25 13:38 UTC, valorkin approved these changes

2018-04-25 13:39 UTC, merged