docs(tooltip): update demos description. Decompose Dynamic Content demo
valor-software/ng2-bootstrap pull request #4154
Opened 2018-03-30 14:27 UTC by YevheniiaMazur

# PR Checklist
 - [ ] built and tested the changes locally.
 - [ ] updated demos.

Closes https://github.com/valor-software/ngx-bootstrap/issues/4148
- `Placement` demo description was updated to following:
![placementtooltipupd](https://user-images.githubusercontent.com/27342505/38141004-0f85a9e6-343f-11e8-8138-94907b83c36a.jpg)
- `Dynamic Content` demo was decomposed. Also, demo description was updated and moved from html template to tooltip-section.list:
![dynamiccontentupd](https://user-images.githubusercontent.com/27342505/38141094-57541bc2-343f-11e8-81b4-8c73b8ede90d.jpg)
- `Dynamic Html` demo description was updated:
![dynamichtmlupd](https://user-images.githubusercontent.com/27342505/38141127-74761ad4-343f-11e8-91f8-81feca4a767f.jpg)
- `Tooltip with delay`: was added description to demo:
![tooltipwithdelupd](https://user-images.githubusercontent.com/27342505/38141158-8bacaa74-343f-11e8-8bbb-37e9ebfd5da5.jpg)

2018-03-30 16:05 UTC, IlyaSurmay requested changes
add new demo files to commit as well

2018-04-02 10:52 UTC, IlyaSurmay requested changes

2018-04-02 10:52 UTC, IlyaSurmay commented on demo/src/app/components/+tooltip/demos/custom-content/custom-content.ts
> +  content: string = 'Vivamus sagittis lacus vel augue laoreet rutrum faucibus.';
remove type annotation

2018-04-02 10:54 UTC, IlyaSurmay approved these changes

2018-04-02 10:58 UTC, IlyaSurmay approved these changes

2018-04-02 16:45 UTC, YevheniiaMazur commented
Tested, looks good

2018-04-05 12:23 UTC, valorkin approved these changes

2018-04-05 12:23 UTC, merged