docs(typeahead): update demos description and fix output
valor-software/ng2-bootstrap pull request #4182
Opened 2018-04-04 12:32 UTC by YevheniiaMazur

# PR Checklist
 - [ ] built and tested the changes locally.
 - [ ] updated demos.

Closes https://github.com/valor-software/ngx-bootstrap/issues/4172
Demo descriptions were updated to following:
- `With delay` and `Template driven forms`, also was fixed output at second demo: 
![delayandtempla](https://user-images.githubusercontent.com/27342505/38307488-91d39cb0-381c-11e8-943d-a3746c807054.jpg)
- `Ignore spaces and order` and `Phrase delimiters`:
![ignorespord](https://user-images.githubusercontent.com/27342505/38307548-b873fe1e-381c-11e8-8530-fe6c4ed478f0.jpg)
- `Append to body`:
![apptobo](https://user-images.githubusercontent.com/27342505/38307580-cc5f0b4e-381c-11e8-8bf1-10377a795d03.jpg)
- `Latinize` and `On select`:
![latonsel](https://user-images.githubusercontent.com/27342505/38307609-e0802e8c-381c-11e8-8242-67e014703805.jpg)
Also code for descriptions at typeahead-section.list was changed for same code style

2018-04-05 11:08 UTC, IlyaSurmay requested changes

2018-04-05 11:08 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +          <p>Output <code>typeaheadOnSelect</code> is fired when an option was selected.
`typeaheadOnSelect` event is fired when...

2018-04-05 11:08 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +          before typeahead kicks-in. In example a typeahead appears with delay in 1 second</p>
`search begins` is better for this demo IMO. a dropdown with suggestions might not appear at all

2018-04-06 11:52 UTC, IlyaSurmay requested changes

2018-04-06 11:52 UTC, IlyaSurmay commented on demo/src/app/components/+typeahead/typeahead-section.list.ts
> +          <p>Output <code>typeaheadOnSelect</code> event is fired when an option was selected.
please remove `Output`

2018-04-06 12:24 UTC, IlyaSurmay approved these changes

2018-04-24 12:03 UTC, valorkin approved these changes

2018-04-24 12:37 UTC, merged