feat(modal): add ability to inject default modal options
valor-software/ng2-bootstrap pull request #4222
Opened 2018-04-13 14:45 UTC by dkosasih

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.

2020-01-19 17:41 UTC, daniloff200 commented
hey, @dkosasih , I see some conflicts here. Could you please fix them?

2020-01-21 10:40 UTC, daniloff200 requested changes

2020-01-21 10:40 UTC, daniloff200 commented on src/spec/modal.default-setting.spec.ts
> +fdescribe('Modal service', () => {
please, remove **f**

2020-01-24 22:53 UTC, dkosasih commented
@daniloff200, I have made the necessary changes. Please have a look.

2020-06-15 13:53 UTC, daniloff200 commented
Well, more than 2 years passed, and looks like, we ready to check that out
Gonna do that this week

2020-06-19 08:14 UTC, daniloff200 approved these changes

2020-06-19 08:16 UTC, merged

2020-09-03 05:12 UTC, wickedsp1d3r commented
I try to use this feature in `AppComponent`:
```
import { MODAL_CONFIG_DEFAULT_OVERRIDE } from 'ngx-bootstrap/modal/modal-options.class';
@Component({
  ...
  providers: [
    ...
    {
      provide: MODAL_CONFIG_DEFAULT_OVERRIDE,
      useValue: { keyboard: false }
    }
    ...
  ]
  ...
})
...
```
Building ends to an error:
```
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/modal/modal-options.class' in <path>\src\app
```
I am using Angular 10.0.14.
Is the cause that Angular does not support deep imports now?
Should `MODAL_CONFIG_DEFAULT_OVERRIDE` be exported from `ngx-bootstrap/modal/public_api.d.ts`?

Thank you for any help!

2020-09-03 15:31 UTC, daniloff200 commented
you can try `ngx-bootstrap/modal` @wickedsp1d3r

2020-09-04 08:05 UTC, dkosasih commented
If this is due to Angular not supporting deep import. We need to expose the `MODAL_CONFIG_DEFAULT_OVERRIDE` through public_api. It's not exported at the moment.

2020-09-04 09:41 UTC, wickedsp1d3r commented
Yes, I get an error if I export it from `ngx-bootstrap/modal`:
```
Module '"../../node_modules/ngx-bootstrap/modal/ngx-bootstrap/modal"' has no exported member 'MODAL_CONFIG_DEFAULT_OVERRIDE'
```

2020-09-04 23:56 UTC, dkosasih commented
yes. That is due to the lack of exposure to public_api. I have open another PR here: https://github.com/valor-software/ngx-bootstrap/pull/5923

2020-09-30 21:23 UTC, eduardoluizm commented
@dkosasih  I have the same error with 6.1.0 version and Angular 10.

"Module not found: Error: Can't resolve 'ngx-bootstrap/modal/modal-options.class'"

How can I fix it?