feat(typeahead): add boolean to show all options on focus if minlength 0
valor-software/ng2-bootstrap pull request #4395
Opened 2018-05-29 14:39 UTC by rbrewington

In earlier versions this was default typeahead behavior
but was eventually called out as a bug and fixed.
However some use cases depended on this behavior.

Closes #3968

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [x] built and tested the changes locally.
 - [x] added/updated tests.
 - [x] added/updated API documentation.
 - [ ] added/updated demos.

2018-09-20 13:16 UTC, rbrewington commented
@Domainv @valorkin Is there anything I need to do to get this one moving?
I notice the codecov patch isn't hitting the mark, but it seems to be referencing code I didn't add anyway.

2020-01-20 09:33 UTC, daniloff200 submitted a review, later dismissed

2020-01-20 10:57 UTC, daniloff200 commented
hey, @rbrewington !
I've fixed one small issue with broken build in your units, but, some tests are still failing
Could you please fix them?

2020-01-21 18:17 UTC, rbrewington commented
@daniloff200 I think the tests should be fixed now. Looks like the number of options in the test typeahead changed, so I replaced the hardcoded value.

2020-02-03 16:11 UTC, daniloff200 commented
@rbrewington  could you please add a small demo, which shows, how the typeahead will work with this parameter?
You can create a new one, or, extend the current one, related to min-length

2020-02-03 16:12 UTC, daniloff200 commented on src/typeahead/typeahead.directive.ts
> +  @Input() typeaheadShowAllOnFocus = false;
I think, it will be not so ofter used property, so, it's more suitable to add it via typeaheadConfig

2020-02-03 16:14 UTC, daniloff200 requested changes
Demo needs to be added
Move new property from Inputs to config

2020-02-07 11:21 UTC, IraErshova requested changes
@rbrewington Hi! Could you please add a demo according to your new functionality? And also it would be better to move `typeaheadShowAllOnFocus` property to **typeahead.config.ts**. As @daniloff200 mentioned it will be using not very often. After that, we will be able to test your PR and merge it.

2020-07-15 15:48 UTC, rbrewington commented
Appears to no longer be necessary. In the latest version, the typeahead shows all the options on focus if typeaheadMinLength is 0.

2020-07-15 15:48 UTC, closed without merging