feat(docs): add POC for use-cases - accordion example
valor-software/ng2-bootstrap pull request #4677
Opened 2018-10-09 09:21 UTC by ludmilanesvitiy

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-10-10 10:51 UTC, OlegDubrovskyi commented on docs/spec/accordion/accordion.examples.group-open.use-case.md
> +
Need to remove extra line

2018-10-10 10:51 UTC, OlegDubrovskyi commented on docs/spec/accordion/accordion.examples.group-open.use-case.md
> +
Need to remove extra line

2018-10-10 10:52 UTC, OlegDubrovskyi commented on docs/spec/accordion/accordion.examples.group-open.use-case.md
> +
Need to remove extra lines

2018-10-10 10:52 UTC, OlegDubrovskyi commented on docs/spec/accordion/accordion.examples.initially-opened.use-case.md
> +
Need to remove extra line

2018-10-10 11:25 UTC, OlegDubrovskyi submitted a review, later dismissed

2018-10-11 08:02 UTC, valorkin requested changes
Same for other versions
When and how svgs are rendered?

2018-10-11 08:02 UTC, valorkin commented on docs/spec/accordion/accordion.examples.basic.use-case.md
> +**Scope**: Ngx-bootstrap DEMO / BS version 4/ v.3.0.1
Remove ngxbs version please
BS version 3&4

2018-10-11 08:37 UTC, ludmilanesvitiy commented
fixed versions for all files
svg generated in online editor https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ
But besides use-case, for generating svg we need to support Mermaid configuration, it's a double work. That's why I don't recommend using it now. This is just example how it could looks like

2018-10-12 10:00 UTC, valorkin approved these changes

2018-10-12 10:00 UTC, valorkin submitted a review, later dismissed

2018-10-17 09:02 UTC, valorkin submitted a review, later dismissed

2018-10-17 10:51 UTC, valorkin approved these changes

2018-10-17 10:51 UTC, merged