feat(docs): added use-cases for pagination component
valor-software/ng2-bootstrap pull request #4684
Opened 2018-10-11 16:26 UTC by OlegDubrovskyi

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-10-12 09:34 UTC, ludmilanesvitiy requested changes

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.basic.use-case.md
> + **Goal**: Show user basic functionality
Show user basic pagination functionality

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.basic.use-case.md
> + 5. After click on 2nd page, previous and next button are enabled, 2ng page is active, 3rd page is inactive
previous and next buttons
2ng page => 2d page

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.boundary-links.use-case.md
> + 2. User clicks on Boundary links event sub-menu
User clicks on Boundary links event sub-menu =>User clicks on Boundary links sub-menu

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.boundary-links.use-case.md
> + 4. After click on 'Last' button, 6th page is active, 1st page is inactive, 'Next' and 'Last' buttons are disabled,
quotes should be the same in each use-case. Please, apply this rule to all use-cases

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.centering-active-page-link.md
> + numbers of page should change on previous 5 pagination pages
rewrite it, pls

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.custom-links-content.use-cases.md
> + 3. Links should be instead  Previous, Next, Last, First text
Links should be instead ? instead of what? look like need rewrite this sentense

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.limits.use-case.md
> + 4. When user clicks on "Next" button and and number of active page link more than center, numbers of page should change
and and

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.limits.use-case.md
> + 5. When user clicks on "Previous" button and and number of active page link less than center, numbers of page should change
and and

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.limits.use-case.md
> + 3. By default maximum page numbers equal to 5.
3. By default maximum page numbers equal to 5 and active page: "1"

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.limits.use-case.md
> + 4. When user clicks on "Next" button and and number of active page link more than center, numbers of page should change
When user clicks on "Next" button, active page should be "2"

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.limits.use-case.md
> + 5. When user clicks on "Previous" button and and number of active page link less than center, numbers of page should change
rewrite other steps, according to rewritten previous

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.manual-switching-page.use-case.md
> + 2. User clicks on Basic sub-menu
3. By default, active page is "4"

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.page-changed-event.use-case.md
> + 2. User clicks on Page changed event sub-menu
3. By default, active page should be...

2018-10-12 09:34 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.pages-count-changed-event.use-case.md
> + 2. User clicks on Page changed event sub-menu
3. By default, ...

2018-10-15 14:31 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.basic.use-case.md
> + 4. When user clicks on 3rd page, then next button is enabled, previous button is disabled, 1st page is inactive
then previous button is enabled, next button is disabled,

2018-10-15 14:31 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.basic.use-case.md
> + 5. After click on 2d page, previous and next button are enabled, 2g page is active, 3rd page is inactive
After click on 2d page, previous and next buttons are enabled, 2d page is active, other pages is inactive

2018-10-15 14:31 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.centering-active-page-link.md
> + 5. When user clicks on 5th page, then active page should 5 and should by center, maximum count of pages should 5
When user click on 5th page, then active page - 5 and it centered, maximum count of pages - 5

2018-10-15 14:31 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.centering-active-page-link.md
> + 5. When user clicks on 5th page, then active page should 5 and should by center, maximum count of pages should 5
rewrite other

2018-10-15 14:31 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.content-switching.use-case.md
> + 4. After click on "Previous" button, pagination content should be changed
After click on "Previous" button, pagination content should be as default

2018-10-15 14:31 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.custom-links-content.use-cases.md
> + 3. Links should be instead  Previous, Next, Last, First text
Instead of text, pagination should be with arrow links "«" and "‹"

2018-10-15 14:31 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.limits.use-case.md
> + 4. When user clicks on 5th page, then active page should 5 and should by center, maximum count of pages should 5
should be

2018-10-15 14:31 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.limits.use-case.md
> + 4. When user clicks on 5th page, then active page should 5 and should by center, maximum count of pages should 5
and rewrite other

2018-10-16 11:45 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.disabled.use-case.md
> + **Goal**: Show user custom links content functionality
rewrite goal

2018-10-16 11:45 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.basic.use-case.md
> + 2*. User scrolls to 'Basic'
'Basic' => "Basic"

2018-10-16 11:45 UTC, ludmilanesvitiy commented on docs/spec/index.md
> +[Examples. Basic](pagination/pagination.examples.basic.use-case.md)
Pagination. Basic
and rewrite other

2018-10-16 11:45 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.pager.use-case.md
> + 2*. User scrolls to 'Pager'
quotes

2018-10-16 11:45 UTC, ludmilanesvitiy commented on docs/spec/pagination/pagination.examples.pages-count-changed-event.use-case.md
> + 2*. User scrolls to 'Pages count changed event'
quotes

2018-10-26 10:03 UTC, ludmilanesvitiy approved these changes

2018-10-26 13:35 UTC, valorkin approved these changes

2018-10-26 13:35 UTC, merged