typeahead: Provide event which caused the selection
valor-software/ng2-bootstrap pull request #4687
Opened 2018-10-15 09:50 UTC by cakeinpanic

I propose the solution for https://github.com/valor-software/ngx-bootstrap/issues/4685 – I suggest providing event(MouseEvent or KeyboardEvent) with emitted TypeaheadMatch

2018-10-28 11:05 UTC, cakeinpanic commented
@valorkin review please

2018-10-28 20:54 UTC, valorkin requested changes

2018-10-28 20:54 UTC, valorkin commented on src/typeahead/typeahead-container.component.ts
> +  selectActiveMatch(e: any): void {
Should have a type
Name should be descriptive
Should be optional or will cause breaking change, and will have to wait for major release to piblish

2018-10-28 20:54 UTC, valorkin commented on src/typeahead/typeahead-container.component.ts
> +    value.selectEvent = e;
I don't see usage of this field, plus it should be set to null on destroy.
Cuz event.target has link to DOM element which in turn could lead to memory leak via detached element persistance
In short: could be deleted?

2020-02-17 09:30 UTC, IraErshova commented
Close this PR because of inactivity. Also, provide another solution for #4685 issue

2020-02-17 09:30 UTC, closed without merging