feat(docs): add use-cases for typeahead component
valor-software/ng2-bootstrap pull request #4688
Opened 2018-10-15 12:29 UTC by kulenkov

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-10-15 13:51 UTC, ludmilanesvitiy requested changes

2018-10-15 13:51 UTC, ludmilanesvitiy commented on demo/src/app/components/+typeahead/demos/async/async.ts
> +     this.typeaheadLoading = e;
not need to touch src code at all

2018-10-15 13:51 UTC, ludmilanesvitiy commented on package-lock.json
> +          "optional": true,
you don't need to change package-lock for this changes. Your changes is related only to documentation. Need to revert other files

2018-10-15 13:51 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.with-delay.use-case.md
> +16.5: Typeahead With daleay example
daleay?

2018-10-15 13:51 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +then a drop-down with a list of States matches is shown
in 1 line

2018-10-15 13:51 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +
7. When user click on any item  in typeahead drop-down, then typeahead container auto-fills with a selected State

2018-10-15 13:51 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.async-data.use-case.md
> +-->
?

2018-10-15 13:51 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.async-data.use-case.md
> +Items quantity in the drop-down is limited with the key `typeaheadOptionsLimit`
Items quantity in the drop-down is limited with the key `typeaheadOptionsLimit` - how?

2018-10-15 13:51 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.basic-array.use-case.md
> +3. User is able to fill the "Model:" input
typeahead input

2018-10-15 13:51 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.basic-array.use-case.md
> +4a. If there is no matches the drop-down is hidden. The "Model" is filled with inputted data
It's not an extension. it should be other step in the scenario

2018-10-15 13:51 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +3. User is able to fill the "Model:" input
User see typeahead input nd typeahead card with "Model:" text

2018-10-16 07:00 UTC, kulenkov commented on package-lock.json
> +          "optional": true,
i even didn't open it

2018-10-16 14:29 UTC, closed without merging