feat(docs): typeahead-use-cases
valor-software/ng2-bootstrap pull request #4696
Opened 2018-10-17 08:16 UTC by kulenkov

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-10-17 14:06 UTC, ludmilanesvitiy requested changes

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +4. When user starts to type a name of a State from "states" array then order of typed symbols and spaces between them is ignored then a drop-down with a list of States matches is shown
then a drop-down => and a drop-down

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +3a. If there is any data, it could be deleted. While deleting data the drop-down with matches is shown
this is an extention not for 3

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +**Goal**: Show user Append to body functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.async-data.use-case.md
> +**Goal**: Show user Async data functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.grouping-results.use-case.md
> +16.8: Typeahead Grouping results  example
results  example - 2 spaces

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.ignore-spaces-order.use-case.md
> +**Goal**: Show user Ignore spaces and symbols order functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.ignore-spaces-order.use-case.md
> +`Default:` the input property is set `typeaheadSingleWords = true`. Order of typed symbols and spaces between them will is ignored
it should be 4th. By default, ...
them will is ?

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.item-template.use-case.md
> +**Goal**: Show user Item template functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.item-template.use-case.md
> +5. When there are any matches then a drop-down with a list of States matches is shown. The list contains a template "This is: "_matched state_" index: _index #"_
there are => there is

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.latinize.use-case.md
> +**Goal**: Show user Latinize functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.no-results.use-case.md
> +**Goal**: Show user No results functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.no-results.use-case.md
> +2. User clicks on No results sub-menu
No result

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.no-results.use-case.md
> +16.14: Typeahead No results example
No result
and rewrite others

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.on-blur.use-case.md
> +**Goal**: Show user On blur functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.on-blur.use-case.md
> +7. If user clicks anywhere outside the input than the "Option on blur" is filled with the first item from the States matches
If user clicks anywhere outside the input than the "Option on blur" is filled with the first item from the States matches - need rewrite.
logic is another.

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.on-select.use-case.md
> +**Goal**: Show user On select functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.on-select.use-case.md
> +2. User click on Selected sub-menu
there is no such menu

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.on-select.use-case.md
> +2*. User scrolls to On selected sub-menu
there is no such menu

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.phrase-delimiters.use-case.md
> +**Goal**: Show user Phrase delimiters functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.phrase-delimiters.use-case.md
> +4. User is able to use "&" and "," to delimit words
question to PO

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +**Goal**: Show user Reactive forms functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +2. User click on Reactive forms forms sub-menu
forms forms

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +5. When user starts to type a name of a State from "states" array and there are no matches then then the drop-down is hidden. The "Model" is filled with inputted data
then then

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +2*. User scrolls to Reactive forms forms sub-menu
forms forms

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.scrollable.use-case.md
> +**Goal**: Show user Scrollable drop-down functionality
rewrite

2018-10-17 14:06 UTC, ludmilanesvitiy commented on docs/spec/typeahead/typeahead.examples.with-delay.use-case.md
> +4. When user starts to type a name of a State from "states" array Drop-dawn update delay depends on key `typeaheadWaitMs`, time delay = 1 sec, by default
Drop-down

2018-10-25 07:55 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +4. When user starts to type a name of a State from "states" array then order of typed symbols and spaces between them is ignored then a drop-down with a list of States matches is shown
fixed

2018-10-25 08:14 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.grouping-results.use-case.md
> +16.8: Typeahead Grouping results  example
fixed

2018-10-25 08:19 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.no-results.use-case.md
> +16.14: Typeahead No results example
fixed

2018-10-25 08:19 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.no-results.use-case.md
> +2. User clicks on No results sub-menu
fixed

2018-10-25 08:22 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.on-blur.use-case.md
> +7. If user clicks anywhere outside the input than the "Option on blur" is filled with the first item from the States matches
fixed

2018-10-25 08:32 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.on-select.use-case.md
> +2. User click on Selected sub-menu
fixed

2018-10-25 08:32 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.on-select.use-case.md
> +2*. User scrolls to On selected sub-menu
fixed

2018-10-25 08:36 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +**Goal**: Show user Reactive forms functionality
fixed

2018-10-25 08:36 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +2. User click on Reactive forms forms sub-menu
fixed

2018-10-25 08:36 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +5. When user starts to type a name of a State from "states" array and there are no matches then then the drop-down is hidden. The "Model" is filled with inputted data
fixed

2018-10-25 08:37 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +2*. User scrolls to Reactive forms forms sub-menu
fixed

2018-10-25 08:37 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.with-delay.use-case.md
> +4. When user starts to type a name of a State from "states" array Drop-dawn update delay depends on key `typeaheadWaitMs`, time delay = 1 sec, by default
fixed

2018-10-25 08:57 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +**Goal**: Show user Append to body functionality
re-written

2018-10-25 08:58 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
> +3a. If there is any data, it could be deleted. While deleting data the drop-down with matches is shown
deleted here and in the other use-cases

2018-10-25 09:22 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.ignore-spaces-order.use-case.md
> +**Goal**: Show user Ignore spaces and symbols order functionality
re-written

2018-10-25 09:24 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.ignore-spaces-order.use-case.md
> +`Default:` the input property is set `typeaheadSingleWords = true`. Order of typed symbols and spaces between them will is ignored
fixed

2018-10-25 09:26 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.item-template.use-case.md
> +**Goal**: Show user Item template functionality
re-written

2018-10-25 09:32 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.item-template.use-case.md
> +5. When there are any matches then a drop-down with a list of States matches is shown. The list contains a template "This is: "_matched state_" index: _index #"_
i'm not sure about these. matches = plural

2018-10-25 09:32 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.latinize.use-case.md
> +**Goal**: Show user Latinize functionality
re-written

2018-10-25 09:35 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.no-results.use-case.md
> +**Goal**: Show user No results functionality
re-written

2018-10-25 09:38 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.on-blur.use-case.md
> +**Goal**: Show user On blur functionality
re-written

2018-10-26 06:52 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.scrollable.use-case.md
> +**Goal**: Show user Scrollable drop-down functionality
re-written

2018-10-26 06:55 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.on-select.use-case.md
> +**Goal**: Show user On select functionality
re-written

2018-10-26 06:58 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.phrase-delimiters.use-case.md
> +**Goal**: Show user Phrase delimiters functionality
re-written

2018-10-26 06:59 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
> +**Goal**: Show user Reactive forms functionality
re-written

2018-10-26 07:00 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.scrollable.use-case.md
> +**Goal**: Show user Scrollable drop-down functionality
re-written

2018-11-06 09:37 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.async-data.use-case.md
> +**Goal**: Show user Async data functionality
re-written

2018-11-06 09:38 UTC, kulenkov commented on docs/spec/typeahead/typeahead.examples.phrase-delimiters.use-case.md
> +4. User is able to use "&" and "," to delimit words
done. steps re-written

2018-11-06 11:40 UTC, ludmilanesvitiy approved these changes

2018-11-06 21:57 UTC, valorkin approved these changes

2018-11-06 21:57 UTC, merged