Feat docs use cases tooltip
valor-software/ng2-bootstrap pull request #4748
Opened 2018-10-29 11:39 UTC by dmitry-zhemchugov

# PR Checklist
Added use-case "Tooltip" 

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-10-31 11:03 UTC, ludmilanesvitiy requested changes
rename directory Tooltip to lowercase

2018-10-31 11:03 UTC, ludmilanesvitiy commented on docs/spec/Tooltip/tooltip.examples.tooltip-with-delay.use-case.md
> +6. Template src should be written with [delay]="500">
remove >

2018-10-31 12:43 UTC, ludmilanesvitiy submitted a review, later dismissed

2018-11-06 21:55 UTC, valorkin submitted a review, later dismissed

2018-11-06 21:56 UTC, valorkin commented on docs/spec/Tooltip/tooltip.examples.tooltip-with-delay.use-case.md
> +6. Template src should be written with [delay]="500">
And follow commit name style guide

2018-11-18 09:20 UTC, valorkin approved these changes

2018-11-18 09:21 UTC, merged