feat(datepicker): allow to select dates from other months
valor-software/ng2-bootstrap pull request #4828
Opened 2018-11-21 14:02 UTC by daniloff200

closes #4485
closes #3746

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-11-26 10:09 UTC, Domainv commented on src/datepicker/themes/bs/bs-datepicker-container.component.ts
> +    if (this.isOtherMonthsActive) {
"if" inside "if" is bad practice.
I suggest using for example:

```
const isDisabled = this.isOtherMonthsActive ? day.isDisabled : (day.isOtherMonth || day.isDisabled);

    if (isDisabled) {
      return;
    }

    this._store.dispatch(this._actions.select(day.date));
```

2018-11-26 10:13 UTC, Domainv commented on src/datepicker/themes/bs/bs-daterangepicker-container.component.ts
> +      if (day.isDisabled) {
same

2018-11-26 10:44 UTC, daniloff200 commented on src/datepicker/themes/bs/bs-daterangepicker-container.component.ts
> +      if (day.isDisabled) {
done

2018-11-26 12:31 UTC, Domainv approved these changes

2018-11-26 14:06 UTC, Domainv requested changes

2018-11-26 14:06 UTC, Domainv commented on src/datepicker/bs-datepicker.config.ts
> +  isOtherMonthsDatesActive = false;
Need to rename similar to other libraries

2018-12-06 09:46 UTC, ludmilanesvitiy commented
New Demo for Datepicker Tested in CHrome, FF - latest, looks good.

2018-12-06 09:57 UTC, Domainv approved these changes

2018-12-06 11:03 UTC, valorkin approved these changes
LGTM

2018-12-06 11:04 UTC, merged