feat(demo): opportunity to change bs theme by url query
valor-software/ng2-bootstrap pull request #4870
Opened 2018-12-03 13:30 UTC by Domainv

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-12-03 16:32 UTC, valorkin requested changes

2018-12-03 16:32 UTC, valorkin commented on demo/src/app/common/sidebar/sidebar.component.ts
> +        this.installTheme(bsVersion);
```suggestion
        this.installTheme(bsVersion || currentTheme);
```

2018-12-03 16:32 UTC, valorkin commented on demo/src/app/common/sidebar/sidebar.component.ts
> +    this.activatedRoute.queryParams
use snapshot of query params

2018-12-04 11:28 UTC, ludmilanesvitiy commented
Smoke tested, looks good.

2018-12-05 18:33 UTC, valorkin approved these changes

2018-12-05 18:33 UTC, merged