tests(tooltip): added e2e test for tooltip
valor-software/ng2-bootstrap pull request #4871
Opened 2018-12-03 13:31 UTC by dmitry-zhemchugov

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2018-12-03 14:08 UTC, ludmilanesvitiy requested changes
1. Need to move basic testing scope to integration/tooltip_page_spec.ts and full scope of tests to full/tooltip_page_spec.ts
2. Need to move all logic to PO methods and reuse it in tests
3. Need to cover each DEMO, according to rule: 1 use-case = 1 describe, 1 step = 1 it
4. Need to make full coverage for all demos inside component

2018-12-21 11:43 UTC, ludmilanesvitiy requested changes

2018-12-21 11:43 UTC, ludmilanesvitiy commented on package-lock.json
> +          "dev": true,
Not need to change package-lock, revert it, pls

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +    const dismissPlacement = tooltip.exampleDemosArr.dismiss;
add blank line

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    this.isTooltipAppearsAndVisible(baseSelector);
isTooltipAppearOnFocus => make just method focusOnTooltip(baseSelector, additionalSelector?:string)

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +  placementsOfTheTooltipContainer = {
tooltipPlacements

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    placementTop: { tooltipContainerClass: 'tooltip in tooltip-top bs-tooltip-top top show', name: 'Tooltip on top' },
top:
right:
auto:
left:
bottom:

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +      tooltipContainerClass: 'tooltip in tooltip-right bs-tooltip-right right show',
containerClass

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +  }
isTooltipPlacementCorrect(baseSelector: string, expectedPlacement) {
     cy.get(`${baseSelector} ${this.togglerTooltip}`)
       .contains(expectedPlacement.name)
       .focus();
 
      cy.get(`${baseSelector} ${this.containerTooltip}`)
       .should('be.visible')
       .should('have.attr', 'class', expectedPlacement.containerClass);
   }

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +  }
isTooltipAppearOnClick => separate to 2 methods, 1 for click, second for check

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${baseSelector} ${this.containerTooltip}`).should('be.visible');
cy.get(`${baseSelector}`).should('to.have.descendants', this.containerTooltip).find(`${this.containerTooltip}`).should('be.visible');

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +  isTooltipDismissAfterTheClicks(baseSelector: string) {
AfterTheClicks?

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${baseSelector}`).closest('.section.bd-example').click();
closest ?

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${baseSelector}`).contains(buttonName).focus();
focus should be in the separate method

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${this.containerTooltip}`).contains('Vivamus sagittis lacus vel augue laoreet rutrum faucibus');
cy.get(`${this.containerTooltip}`).contains('Vivamus sagittis lacus vel augue laoreet rutrum faucibus'); - for what?

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${baseSelector} ${this.togglerTooltip}`).focus();
this method not necessary, because you'll move focus to other method. In this case you'll use 2 methods directly in test

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    }
add blank line under

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${this.containerTooltip}`).should('be.visible').contains(tooltipText);
rework with chain

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +  isCustomTriggersClickAppearsAndVisible(baseSelector: string, buttonName: string, tiggerEvent: string, tooltipText: string) {
not descriptive name

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${baseSelector}`).should('not.to.have.descendants', this.containerTooltip);
need to investigate, maybe this method could be shortened

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${baseSelector}`).should('not.to.have.descendants', this.containerTooltip);
all such actions + assertions should not be in 1 method. For click on buttons use method from base component

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    cy.get(`${baseSelector}`).should('not.to.have.descendants', this.containerTooltip);
need rework according to the previous comment

2018-12-21 11:43 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +  }
need to remove it and reuse method from base component

2018-12-21 12:36 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +      tooltipContainerClass: 'tooltip in tooltip-right bs-tooltip-right right show',
bs-tooltip-right

2019-01-11 12:31 UTC, ludmilanesvitiy requested changes

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +    const basic = tooltip.exampleDemosArr.placement;
const basic => const placementDemo

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +    const dismissPlacement = tooltip.exampleDemosArr.dismiss;
const dismissPlacement => const dismiss or const dismissDemo

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +    const dynamicContentPlacement = tooltip.exampleDemosArr.dynamicTooltip;
dynamicContent

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +    it('when user on hovering on trigger btn in the Placement exmpl - tooltip appears on the setted placement', () => {
when user hover on Trigger btn

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +      tooltip.focusOnTooltip(dynamicContentPlacement);
clickOnTooltip

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +      tooltip.focusOnTooltip(customContentTemplate);
clickOnTooltip

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    dynamicHtmlButton: 'demo-tooltip-dynamic-html',
dynamicHtml

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    defaultTooltip: 'demo-tooltip-container',
appendToBody

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +      tooltip.focusOnTooltip(configuringDefaultsTooltip);
click

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/integration/tooltip_page_spec.ts
> +    it('when the user on hovering on the trigger btn, tooltip appears and dismiss after mouse leave', () => {
...user hover on the trigger btn...

2019-01-11 12:31 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +  }
need to remove it and reuse method from base component

2019-01-15 12:26 UTC, ludmilanesvitiy commented on cypress/full/tooltip_page_spec.ts
> +    it('when user clicks on the Configuring tooltip btn, Tooltip appears & dismiss after mouse leave', () => {
& dismiss after mouse leave - looks like need to remove it

2019-01-15 12:26 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    dynamicHtmlButton: 'demo-tooltip-dynamic-html',
just dynamicHtml

2019-01-15 12:26 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +    defaultTooltip: 'demo-tooltip-container',
appendToBody

2019-01-15 12:26 UTC, ludmilanesvitiy commented on cypress/support/tooltip.po.ts
> +  }
need to remove it and reuse method from base component

2019-01-15 13:27 UTC, ludmilanesvitiy approved these changes

2019-02-05 11:35 UTC, valorkin approved these changes

2019-02-06 15:25 UTC, valorkin approved these changes

2019-02-06 15:26 UTC, merged

2019-02-06 15:26 UTC, valorkin commented
@dmitry-zhemchugov use commit convention properly
it's tests(tooltip) not feat(tests)

2019-02-07 03:01 UTC, dmitry-zhemchugov commented
via Hubstaff
User: Dmitry Zhemchugov

Project: int_ngx-bootstrap (OSS) - https://app.hubstaff.com/projects/304822
Date Range: 01/16/19 - 01/16/19
Work session total: 0:00:10

Grand total: 0:00:10