feat(tests): add full e2e coverage for Popover component
valor-software/ng2-bootstrap pull request #5001
Opened 2019-01-10 13:54 UTC by dmitry-zhemchugov

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2019-01-11 12:34 UTC, ludmilanesvitiy commented
@dmitry-zhemchugov All PR labels should be similar to https://github.com/valor-software/ngx-bootstrap/pull/4871

2019-01-11 12:48 UTC, ludmilanesvitiy requested changes

2019-01-11 12:48 UTC, ludmilanesvitiy commented on cypress/full/popover_page_spec.ts
> +    const basic = popover.exampleDemosArr.placement;
placementDemo

2019-01-11 12:48 UTC, ludmilanesvitiy commented on cypress/support/base.component.ts
> +  typeOnInput(baseSelector: string, forInput: string, inputIndex?: number) {
same as clearInputAndSendKeys method, in this class

2019-01-11 12:48 UTC, ludmilanesvitiy commented on cypress/support/base.component.ts
> +  typeOnInput(baseSelector: string, forInput: string, inputIndex?: number) {
need to remove it

2019-01-11 12:48 UTC, ludmilanesvitiy commented on cypress/support/popover.po.ts
> +    eventTextBlock: 'pre.card.card-block.card-header.mb-3',
1. bad selector, need to find more stable
2. it should be not in the exampleDemosArr

2019-01-11 12:48 UTC, ludmilanesvitiy commented on cypress/support/popover.po.ts
> +  isEventShown(baseSelector1: string) {
what does it mean baseSelector1 ?

2019-01-11 12:48 UTC, ludmilanesvitiy commented on cypress/support/popover.po.ts
> +  isEventHidden(baseSelector1: string) {
what does it mean baseSelector1 ?

2019-01-14 10:28 UTC, ludmilanesvitiy commented on cypress/full/popover_page_spec.ts
> +        popover.clickOnBtn(configuringDefaults);
2

2019-01-14 10:28 UTC, ludmilanesvitiy commented on cypress/integration/popover_page_spec.ts
> +  before(() => popover.navigateTo());
beforeEach

2019-01-14 10:28 UTC, ludmilanesvitiy commented on cypress/integration/popover_page_spec.ts
> +      popover.clickOnBtn(basicPopover);
2

2019-01-14 14:29 UTC, valorkin approved these changes

2019-01-14 14:29 UTC, merged