WIP: test(common): update all tests according to the common approach
valor-software/ng2-bootstrap pull request #5092
Opened 2019-03-06 16:51 UTC by kulenkov

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2019-03-11 10:38 UTC, ludmilanesvitiy requested changes

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/integration/landing_page_spec.ts
> +      landing.isElementVisible(landing.mainClass, landing.logoAtContent);
move this checks into previous 'it'. If you don't make any actions, and make only assertions - better to serve them in 1 'it'

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/landing.po.ts
> +  loadBootstrapVersion(bsVersion: number) {
visitNGXBootstrapWithBsVersion

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/integration/landing_page_spec.ts
> +    const bootStrapVer3 = '3';
remove

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/integration/landing_page_spec.ts
> +    const bootStrapVer4 = '4';
remove

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/integration/landing_page_spec.ts
> +    it('the 3rd version is ', () => {
const bsVersion = 3;

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/integration/landing_page_spec.ts
> +      landing.loadBootstrapVersion(3);
use bsVersion instead of number

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/integration/landing_page_spec.ts
> +    it('the 4th version is ', () => {
const bsVersion = 4;

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/base.component.ts
> +  isUrlExist(urlToCheck: string) {
urlToCheck => expectedUrl

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/base.component.ts
> +  isElemHasCorrectUrl(elementSelector: string, link: string) {
link => expectedUrl

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/base.component.ts
> +      .and('equal', link);
to.equal

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/landing.po.ts
> +  stackOverBtn = 'li:nth-child(1) a';
a[href*= "stackoverflow"]

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/landing.po.ts
> +  gitHbBtn = 'li:nth-child(2) a';
.header-list a[href*= "github"]

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/landing.po.ts
> +  slackNgxBtn = 'li:nth-child(3) a';
.header-list a[href*= "slack"]

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/landing.po.ts
> +  clickOnMenuBtn() {
clickOnMobileMenuBtn

2019-03-11 10:38 UTC, ludmilanesvitiy commented on cypress/support/landing.po.ts
> +  isMenuHasDescendants(descen1Selector: string, descen2Selector: string) {
isMobileMenuHasDescendants

2019-03-13 08:27 UTC, ludmilanesvitiy submitted a review, later dismissed

2019-03-18 09:10 UTC, Domainv commented
Needs to resolve confilcts

2019-03-18 10:29 UTC, ludmilanesvitiy approved these changes

2019-03-18 16:28 UTC, merged