WIP. feat(carousel): allow to display multiple items per one slide
valor-software/ng2-bootstrap pull request #5133
Opened 2019-03-28 14:13 UTC by musienkoyuriy

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2019-04-15 08:23 UTC, ludmilanesvitiy commented
1. Open Carousel demo page, take a look at console log:
![Screenshot from 2019-04-15 10-28-19](https://user-images.githubusercontent.com/18209841/56114343-3e1fff80-5f69-11e9-8d02-f6279ff1abdc.png)

2. Broken existed functionality, STR:
- Open https://valor-software.com/ngx-bootstrap/#/carousel#captions
-  When shown the First slide, click on left arrow "<"
-  Observe the results: latest (Third) slide is active

In current implementation: first slide item will not switch to third.
![Peek 2019-04-15 10-41](https://user-images.githubusercontent.com/18209841/56114992-16319b80-5f6b-11e9-9d80-47d2600e9814.gif)

3. Similar issue with switching item from 3d to the 1st. (reproduced by tests in Disable slide looping)

2019-04-16 09:21 UTC, ludmilanesvitiy commented on package.json
> +    "build.carousel": "rimraf dist/carousel && node scripts/ng-packagr/api ../../src/carousel/package.json"
why do we need it?

2019-04-16 09:21 UTC, ludmilanesvitiy commented
Rechecked existed and new functionality - looks good. Smoke tested in Chrome, FF, IE.

2019-04-16 09:25 UTC, musienkoyuriy commented on package.json
> +    "build.carousel": "rimraf dist/carousel && node scripts/ng-packagr/api ../../src/carousel/package.json"
it was just for my personal convenience and it is temporary (to build just my module during the work with it). As all is ok, I going to delete it

2019-04-17 13:50 UTC, Domainv requested changes

2019-04-17 13:50 UTC, Domainv commented on src/carousel/carousel.component.ts
> +    setTimeout(() => {
Are we sure we can't do without it?

2019-04-17 14:34 UTC, Domainv commented on src/carousel/carousel.component.ts
> +    setTimeout(() => {
check

2019-04-17 16:01 UTC, Domainv submitted a review, later dismissed

2019-04-22 12:24 UTC, ludmilanesvitiy commented
Smoke retested in Chrome, Edge - looks good.

2019-04-22 13:36 UTC, Domainv approved these changes

2019-04-22 13:37 UTC, merged