Fixed broken image link for 'Sauce Labs'
valor-software/ng2-bootstrap pull request #5483
Opened 2019-10-13 12:07 UTC by hajro92

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [X] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ X] built and tested the changes locally.
 - [X ] added/updated tests.
 - [X ] added/updated API documentation.
 - [ X] added/updated demos.

2019-10-13 20:29 UTC, daniloff200 commented
I actually don't like the idea to use pic from Twitter.
Can you please replace it with https://avatars2.githubusercontent.com/u/88837?s=200&v=4 ?

2019-10-13 20:29 UTC, daniloff200 requested changes
need to change url

2019-10-14 15:31 UTC, daniloff200 approved these changes

2019-10-17 08:40 UTC, Domainv approved these changes

2019-10-17 08:41 UTC, merged

2019-10-17 14:02 UTC, daniloff200 commented
hey @hajro92 !
Thanks again for the PR!
Could you please fill out this [form](https://docs.google.com/forms/d/1tHjwGbh8CIrLcOjcMOHoY7xiLNXpQWNXySwhJbwNrH8/edit) so we can send some swag to you? Thanks!