Switch to new GitHub multi ISSUE_TEMPLATEs
valor-software/ng2-bootstrap pull request #5492
Opened 2019-10-13 16:59 UTC by amithkk

Fixes #5491  , switches to new github issue templates

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.

2019-10-13 20:24 UTC, daniloff200 requested changes
Hey! I really like that change!

But, got couple of improvements
1) Maybe,  we should add  Custom issue, if it's not related to both two, added by you. For example, as this one: https://github.com/accordproject/techdocs/issues/new?assignees=&labels=&template=custom-issue.md&title=

2) I see, that <!--- comments doesn't work, you can see that even in your forked repo, while trying to create an issue:  https://github.com/amithkk/ngx-bootstrap/issues/new?assignees=&labels=bug&template=bug-report-.md&title=

maybe just remove that?

2019-10-14 17:04 UTC, amithkk commented
Hey!

I've done both of those things but from my end I can see that the comments do pop up in the editing view but don't come up on the preview (which was the intention)

![image](https://user-images.githubusercontent.com/1029727/66769335-7f6e7900-eed2-11e9-96a5-6fe12a465eb0.png)

2019-10-17 08:31 UTC, daniloff200 approved these changes

2019-10-17 08:35 UTC, Domainv approved these changes

2019-10-17 08:36 UTC, merged

2019-10-17 14:02 UTC, daniloff200 commented
hey @amithkk !
Thanks again for the PR!
Could you please fill out this [form](https://docs.google.com/forms/d/1tHjwGbh8CIrLcOjcMOHoY7xiLNXpQWNXySwhJbwNrH8/edit) so we can send some swag to you? Thanks!