fix(typeahead): fix focus after leaving control (#4622) [WIP]
valor-software/ng2-bootstrap pull request #5593
Opened 2020-01-11 10:20 UTC by daniloff200

Co-authored-by: Dmitriy Danilov <daniloff200@gmail.com>

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ ] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

That's another PR, which related to #4622, cause, fork was deleted, and it need some fixes

2020-01-14 12:02 UTC, valorkin requested changes

2020-01-14 12:02 UTC, valorkin commented on src/typeahead/typeahead.directive.ts
> +  @Input() typeaheadCancelOnBlur = false;
this option will not be changed too often, please move to it to config,
to avoid Component bloating

2020-01-24 14:15 UTC, valorkin requested changes
naming, please

2020-01-24 14:15 UTC, valorkin commented on src/typeahead/typeahead.config.ts
> +  typeaheadCancelOnBlur = false;
cancelRequestOnFocusLost

2020-01-24 14:15 UTC, valorkin commented on src/typeahead/typeahead.directive.ts
> +        typeaheadCancelOnBlur: config.typeaheadCancelOnBlur,
rename here to

2020-01-31 11:20 UTC, valorkin approved these changes
Looks good to me!

2020-02-05 13:43 UTC, dmitry-zhemchugov commented
Tested this PR. Ready for merge.

2020-02-05 15:06 UTC, merged