feat(tooltip): add functionality, which hide tooltip after delay
valor-software/ng2-bootstrap pull request #5599
Opened 2020-01-16 15:25 UTC by daniloff200

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ ] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2020-01-28 15:17 UTC, IraErshova commented on demo/src/ng-api-doc.ts
> +        "description": "<p>delay before showing the popover</p>\n"
Did you add this code by thy script or manually?

2020-01-28 15:18 UTC, IraErshova commented on src/popover/popover.directive.ts
> +  @Input() hideAfterDelay: number;
I think new properties we should add via Config, shouldn't we?

2020-01-28 15:19 UTC, IraErshova commented on src/tooltip/tooltip.directive.ts
> +  @Input() hideAfterDelay: number;
the same about Config

2020-01-29 12:41 UTC, daniloff200 commented
hey, @dmitry-zhemchugov , I will need your help with fixing my e2e tests later :)

2020-02-26 10:30 UTC, dmitry-zhemchugov commented
Need fix regarding cooldown of tooltip @daniloff200

2020-02-26 10:30 UTC, dmitry-zhemchugov requested changes
Need fix.

2021-02-09 07:40 UTC, daniloff200 commented
Project: ngx-bootstrap-demo 
 Url: https://ngx-bootstrap-demo--pr-5599-pccirowb.web.app 
 This link will expire at Thu 11 Mar 2021 07:40:19 AM GMT

2022-02-22 03:31 UTC, giovannidias1 commented
por que este PR ainda está aberto

2022-10-16 15:20 UTC, closed without merging