fix(dropdown): fix for animation of a dropdown that has *ngIf set for…
valor-software/ng2-bootstrap pull request #5687
Opened 2020-02-24 09:32 UTC by sonicpro

… some list items

The dropdown container height is calcuated incorrectly if at the moment the animation starts the view is not initialized.

Closes #5602

# PR Checklist
Before creating new PR, please take a look at checklist below to make sure that you've done everything that needs to be done before we can merge it.

 - [ x] read and followed the [CONTRIBUTING.md](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md) guide.
 - [ x] built and tested the changes locally.
 - [ ] added/updated tests.
 - [ ] added/updated API documentation.
 - [ ] added/updated demos.

2020-02-24 10:22 UTC, daniloff200 approved these changes

2020-02-27 11:25 UTC, dmitry-zhemchugov commented
Tested. Ready to merge.

2020-02-27 11:36 UTC, IraErshova approved these changes

2020-02-27 11:41 UTC, valorkin requested changes

2020-02-27 11:41 UTC, valorkin commented on src/dropdown/bs-dropdown-container.component.ts
> +  ngAfterViewInit(): void {
@sonicpro I believe this should be after content ivent, because `.dropdown-menu` is in content, not in html of this component

2020-02-28 10:31 UTC, dmitry-zhemchugov commented
Nothing fixed on dropdowns. Need fix.
![issue](https://user-images.githubusercontent.com/44227371/75541235-356fd500-5a26-11ea-8e16-7166243133b9.jpg)

2020-04-09 19:13 UTC, daniloff200 commented
Closed, issue was fixed in another PR
#5755

2020-04-12 16:10 UTC, closed without merging