Fix(datepicker):  ranges and  max date
valor-software/ng2-bootstrap pull request #6156
Opened 2021-05-28 11:14 UTC by SvetlanaMuravlova

maxDate and maxDateRange not working properly when used together in ngx-bootstrap date range picker
refs #6105

2021-05-28 11:22 UTC, daniloff200 submitted a review, later dismissed

2021-05-31 10:07 UTC, daniloff200 submitted a review, later dismissed

2021-05-31 10:35 UTC, valorkin requested changes
Missing semicolons

2021-05-31 16:01 UTC, valorkin requested changes
Please address comments

2021-05-31 16:01 UTC, valorkin commented on src/datepicker/bs-daterangepicker.component.ts
> +    if (!ranges || !maxDate || (ranges && !ranges.length && !ranges[0].value)) return ranges;
Please extract this method to helper file and cover with tests.
And don't nest ifs, prefer guard checks and early exits

2021-06-01 08:19 UTC, valorkin commented
+ apply to other rangepickers as well

2021-07-07 12:30 UTC, valorkin approved these changes

2021-07-07 12:30 UTC, merged