fix(datepicker): added optional time initing
valor-software/ng2-bootstrap pull request #6288
Opened 2021-09-10 10:22 UTC by SvetlanaMuravlova

fix(datepicker): added optional time initing
closes #6276  #6260

2021-09-10 19:30 UTC, daniloff200 submitted a review, later dismissed

2021-09-21 08:26 UTC, valorkin requested changes
please apply comments

2021-09-21 08:26 UTC, valorkin commented on src/datepicker/bs-datepicker-inline.component.ts
> +  @Input() set bsConfig(value: Partial<BsDatepickerInlineConfig>) {
move to ngOnChanges

2021-09-21 08:26 UTC, valorkin commented on src/datepicker/bs-datepicker-inline.component.ts
> +    this._config = Object.assign({}, this._config, this._bsConfig, {
revert

2021-09-24 10:57 UTC, valorkin submitted a review, later dismissed

2021-09-24 12:14 UTC, merged