fix(datepicker): fixed inline datepicker subscriptions
valor-software/ng2-bootstrap pull request #6339
Opened 2021-10-29 08:45 UTC by SvetlanaMuravlova

fix(datepicker): fixed inline datepicker subscriptions
close #6263 

What to test:
In inline datepicker and daterangepicker was fixed subscriptions

Preconditions:
use local version from this branch for reproducing this fix from issue

How to test:
on local version try reproducing as in issue example

2021-10-29 10:44 UTC, apotapcukv submitted a review, later dismissed

2021-12-23 15:00 UTC, valorkin requested changes
unsubscribe should be in all versions I suppose

2021-12-23 15:00 UTC, valorkin commented on src/datepicker/bs-datepicker-inline.component.ts
> +    this._subs = [];
```suggestion
```

2021-12-23 15:00 UTC, valorkin commented on src/datepicker/bs-datepicker-inline.component.ts
> +      this._subs.map(sub => sub.unsubscribe());
```suggestion
      this._subs.map(sub => sub.unsubscribe());
      this._subs.length = 0;
```

2022-01-13 10:27 UTC, valorkin approved these changes

2022-01-13 10:27 UTC, merged